/**
 * 66-book Bible canon metadata used by both the English and Tamil DBs.
 * Aliases include English abbreviations, Tamil names, partial Tamil prefixes,
 * and Tanglish (romanised Tamil) variants — the fuzzy search engine matches
 * against this list with prefix, exact, and edit-distance scoring.
 */
export interface BibleBookMeta {
  index: number;
  code: string;
  name: string;
  nameTa: string;
  chapters: number;
  aliases: string[];
  testament: "OT" | "NT";
}

const make = (
  index: number,
  code: string,
  name: string,
  nameTa: string,
  chapters: number,
  aliases: string[],
  testament: "OT" | "NT",
): BibleBookMeta => ({
  index,
  code,
  name,
  nameTa,
  chapters,
  testament,
  aliases: Array.from(
    new Set([
      name.toLowerCase(),
      name.toLowerCase().replace(/\s+/g, ""),
      code.toLowerCase(),
      nameTa,
      nameTa.replace(/\s+/g, ""),
      ...aliases.map((a) => a.toLowerCase()),
    ]),
  ),
});

// Tamil and Tanglish abbreviations come from common usage in Tamil churches.
export const BIBLE_BOOKS: BibleBookMeta[] = [
  make(
    0,
    "GEN",
    "Genesis",
    "ஆதியாகமம்",
    50,
    ["gen", "ge", "gn", "genisis", "genesys", "aathi", "aadhi", "aadi", "ஆதி", "ஆதிய"],
    "OT",
  ),
  make(
    1,
    "EXO",
    "Exodus",
    "யாத்திராகமம்",
    40,
    ["exo", "ex", "exod", "exudus", "exidus", "yathira", "yaathira", "யாத்", "யாத்திரா"],
    "OT",
  ),
  make(
    2,
    "LEV",
    "Leviticus",
    "லேவியராகமம்",
    27,
    ["lev", "le", "lv", "leviticus", "leviyar", "leviyara", "லேவி", "லேவியர"],
    "OT",
  ),
  make(
    3,
    "NUM",
    "Numbers",
    "எண்ணாகமம்",
    36,
    ["num", "nu", "nm", "nb", "ennaa", "ennakamam", "ennaagamam", "எண்", "எண்ணா"],
    "OT",
  ),
  make(
    4,
    "DEU",
    "Deuteronomy",
    "உபாகமம்",
    34,
    ["deu", "dt", "deut", "upakamam", "ubakamam", "upa", "உப", "உபா"],
    "OT",
  ),
  make(5, "JOS", "Joshua", "யோசுவா", 24, ["jos", "josh", "jsh", "yosuva", "yoshua", "யோசு"], "OT"),
  make(
    6,
    "JDG",
    "Judges",
    "நியாயாதிபதிகள்",
    21,
    ["jdg", "judg", "jg", "judges", "niyaayaa", "niyaya", "niyayadhibathigal", "நியா"],
    "OT",
  ),
  make(7, "RUT", "Ruth", "ரூத்", 4, ["rut", "ru", "rth", "ruth", "ரூத"], "OT"),
  make(
    8,
    "1SA",
    "1 Samuel",
    "1 சாமுவேல்",
    31,
    ["1sa", "1 sam", "1sam", "1 sa", "1s", "1 samuvel", "1samuvel", "1 saamuvel", "1 சாமு"],
    "OT",
  ),
  make(
    9,
    "2SA",
    "2 Samuel",
    "2 சாமுவேல்",
    24,
    ["2sa", "2 sam", "2sam", "2 sa", "2s", "2 samuvel", "2samuvel", "2 சாமு"],
    "OT",
  ),
  make(
    10,
    "1KI",
    "1 Kings",
    "1 இராஜாக்கள்",
    22,
    ["1ki", "1 ki", "1 kgs", "1kgs", "1k", "1 rajakkal", "1rajakkal", "1 இராஜா"],
    "OT",
  ),
  make(
    11,
    "2KI",
    "2 Kings",
    "2 இராஜாக்கள்",
    25,
    ["2ki", "2 ki", "2 kgs", "2kgs", "2k", "2 rajakkal", "2rajakkal", "2 இராஜா"],
    "OT",
  ),
  make(
    12,
    "1CH",
    "1 Chronicles",
    "1 நாளாகமம்",
    29,
    ["1ch", "1 chr", "1chr", "1 ch", "1 naalaa", "1naalaa", "1 நாளா"],
    "OT",
  ),
  make(
    13,
    "2CH",
    "2 Chronicles",
    "2 நாளாகமம்",
    36,
    ["2ch", "2 chr", "2chr", "2 ch", "2 naalaa", "2naalaa", "2 நாளா"],
    "OT",
  ),
  make(14, "EZR", "Ezra", "எஸ்றா", 10, ["ezr", "ez", "ezra", "esra", "எஸ்", "எஸ்றா"], "OT"),
  make(15, "NEH", "Nehemiah", "நெகேமியா", 13, ["neh", "ne", "nehemiah", "negemiya", "நெகே"], "OT"),
  make(16, "EST", "Esther", "எஸ்தர்", 10, ["est", "es", "esth", "esther", "ester", "எஸ்த"], "OT"),
  make(17, "JOB", "Job", "யோபு", 42, ["job", "jb", "yobu", "yopu", "யோபு"], "OT"),
  make(
    18,
    "PSA",
    "Psalms",
    "சங்கீதம்",
    150,
    [
      "psa",
      "ps",
      "pslm",
      "psalm",
      "psalms",
      "pss",
      "pslam",
      "sangee",
      "sangeetham",
      "sangeedham",
      "sangidham",
      "சங்",
      "சங்கீ",
    ],
    "OT",
  ),
  make(
    19,
    "PRO",
    "Proverbs",
    "நீதிமொழிகள்",
    31,
    ["pro", "pr", "prov", "prv", "proverbs", "neethi", "needhi", "நீதி"],
    "OT",
  ),
  make(
    20,
    "ECC",
    "Ecclesiastes",
    "பிரசங்கி",
    12,
    ["ecc", "ec", "eccl", "qoh", "prasangi", "pirasangi", "பிரச"],
    "OT",
  ),
  make(
    21,
    "SNG",
    "Song of Solomon",
    "உன்னதப்பாட்டு",
    8,
    ["sng", "song", "sos", "ss", "cant", "unnatha", "unnathapaattu", "உன்ன"],
    "OT",
  ),
  make(22, "ISA", "Isaiah", "ஏசாயா", 66, ["isa", "is", "isaiah", "esaya", "ஏசாயா", "ஏசா"], "OT"),
  make(
    23,
    "JER",
    "Jeremiah",
    "எரேமியா",
    52,
    ["jer", "je", "jr", "jeremiah", "eremiya", "எரேமியா", "எரே"],
    "OT",
  ),
  make(24, "LAM", "Lamentations", "புலம்பல்", 5, ["lam", "la", "pulambal", "புலம்"], "OT"),
  make(
    25,
    "EZK",
    "Ezekiel",
    "எசேக்கியேல்",
    48,
    ["ezk", "eze", "ezek", "esekiyel", "esekkiyel", "எசேக்", "எசே"],
    "OT",
  ),
  make(
    26,
    "DAN",
    "Daniel",
    "தானியேல்",
    12,
    ["dan", "da", "dn", "daniel", "thaniyel", "தானி"],
    "OT",
  ),
  make(27, "HOS", "Hosea", "ஓசியா", 14, ["hos", "ho", "hosea", "osiya", "ஓசி"], "OT"),
  make(28, "JOL", "Joel", "யோவேல்", 3, ["jol", "joel", "joe", "jl", "yovel", "யோவே"], "OT"),
  make(29, "AMO", "Amos", "ஆமோஸ்", 9, ["amo", "am", "amos", "aamos", "ஆமோ"], "OT"),
  make(
    30,
    "OBA",
    "Obadiah",
    "ஒபதியா",
    1,
    ["oba", "ob", "obadiah", "opathiya", "obadhiya", "ஒபதி"],
    "OT",
  ),
  make(31, "JON", "Jonah", "யோனா", 4, ["jon", "jnh", "jonah", "yona", "யோனா"], "OT"),
  make(32, "MIC", "Micah", "மீகா", 7, ["mic", "mi", "micah", "meega", "மீகா"], "OT"),
  make(33, "NAM", "Nahum", "நாகூம்", 3, ["nam", "nah", "na", "nahum", "naagoom", "நாகூ"], "OT"),
  make(34, "HAB", "Habakkuk", "ஆபகூக்", 3, ["hab", "hb", "habakkuk", "aabakook", "ஆபகூ"], "OT"),
  make(35, "ZEP", "Zephaniah", "செப்பனியா", 3, ["zep", "zeph", "zp", "seppaniya", "செப்ப"], "OT"),
  make(
    36,
    "HAG",
    "Haggai",
    "ஆகாய்",
    2,
    ["hag", "hg", "haggai", "aakaai", "aakai", "ஆகாய்", "ஆகா"],
    "OT",
  ),
  make(
    37,
    "ZEC",
    "Zechariah",
    "சகரியா",
    14,
    ["zec", "zech", "zc", "zechariah", "sakariya", "சகரி"],
    "OT",
  ),
  make(38, "MAL", "Malachi", "மல்கியா", 4, ["mal", "ml", "malachi", "malkiya", "மல்கி"], "OT"),
  make(
    39,
    "MAT",
    "Matthew",
    "மத்தேயு",
    28,
    ["mat", "mt", "matt", "matthew", "mathew", "mathayu", "matteyu", "மத்", "மத்தே"],
    "NT",
  ),
  make(
    40,
    "MRK",
    "Mark",
    "மாற்கு",
    16,
    ["mrk", "mk", "mr", "mark", "maaku", "marku", "maarku", "மாற்", "மாற்கு"],
    "NT",
  ),
  make(
    41,
    "LUK",
    "Luke",
    "லூக்கா",
    24,
    ["luk", "lk", "lu", "luke", "luka", "looka", "லூக்", "லூக்கா"],
    "NT",
  ),
  make(
    42,
    "JHN",
    "John",
    "யோவான்",
    21,
    ["jhn", "jn", "joh", "john", "yovan", "yovaan", "yova", "yo", "யோவா", "யோவான்", "யோ"],
    "NT",
  ),
  make(
    43,
    "ACT",
    "Acts",
    "அப்போஸ்தலர்",
    28,
    ["act", "ac", "acts", "appostalar", "apposthalar", "அப்போ"],
    "NT",
  ),
  make(
    44,
    "ROM",
    "Romans",
    "ரோமர்",
    16,
    ["rom", "ro", "rm", "romans", "romar", "ரோமர்", "ரோம"],
    "NT",
  ),
  make(
    45,
    "1CO",
    "1 Corinthians",
    "1 கொரிந்தியர்",
    16,
    ["1co", "1 cor", "1cor", "1 co", "1 korinthi", "1korinthi", "1 கொரி"],
    "NT",
  ),
  make(
    46,
    "2CO",
    "2 Corinthians",
    "2 கொரிந்தியர்",
    13,
    ["2co", "2 cor", "2cor", "2 co", "2 korinthi", "2korinthi", "2 கொரி"],
    "NT",
  ),
  make(
    47,
    "GAL",
    "Galatians",
    "கலாத்தியர்",
    6,
    ["gal", "ga", "galatians", "kalathiyar", "கலாத்"],
    "NT",
  ),
  make(
    48,
    "EPH",
    "Ephesians",
    "எபேசியர்",
    6,
    ["eph", "ep", "ephesians", "epesiyar", "எபேசி"],
    "NT",
  ),
  make(
    49,
    "PHP",
    "Philippians",
    "பிலிப்பியர்",
    4,
    ["php", "phil", "pp", "philippians", "pilippiyar", "பிலிப்"],
    "NT",
  ),
  make(
    50,
    "COL",
    "Colossians",
    "கொலோசேயர்",
    4,
    ["col", "co", "colossians", "koloseyar", "கொலோ"],
    "NT",
  ),
  make(
    51,
    "1TH",
    "1 Thessalonians",
    "1 தெசலோனிக்கேயர்",
    5,
    ["1th", "1 thess", "1thess", "1 th", "1 thesalo", "1thesalo", "1 தெசலோ"],
    "NT",
  ),
  make(
    52,
    "2TH",
    "2 Thessalonians",
    "2 தெசலோனிக்கேயர்",
    3,
    ["2th", "2 thess", "2thess", "2 th", "2 thesalo", "2thesalo", "2 தெசலோ"],
    "NT",
  ),
  make(
    53,
    "1TI",
    "1 Timothy",
    "1 தீமோத்தேயு",
    6,
    ["1ti", "1 tim", "1tim", "1 ti", "1 thimothey", "1thimothey", "1 தீமோ"],
    "NT",
  ),
  make(
    54,
    "2TI",
    "2 Timothy",
    "2 தீமோத்தேயு",
    4,
    ["2ti", "2 tim", "2tim", "2 ti", "2 thimothey", "2thimothey", "2 தீமோ"],
    "NT",
  ),
  make(55, "TIT", "Titus", "தீத்து", 3, ["tit", "ti", "titus", "theethu", "தீத்"], "NT"),
  make(
    56,
    "PHM",
    "Philemon",
    "பிலேமோன்",
    1,
    ["phm", "philem", "pm", "philemon", "pilemon", "பிலே"],
    "NT",
  ),
  make(57, "HEB", "Hebrews", "எபிரெயர்", 13, ["heb", "he", "hebrews", "epireyar", "எபிரெ"], "NT"),
  make(
    58,
    "JAS",
    "James",
    "யாக்கோபு",
    5,
    ["jas", "jm", "james", "yakkobu", "yaakkobu", "யாக்", "யாக்கோ"],
    "NT",
  ),
  make(
    59,
    "1PE",
    "1 Peter",
    "1 பேதுரு",
    5,
    ["1pe", "1 pet", "1pet", "1 pe", "1p", "1 pethuru", "1pethuru", "1 பேது"],
    "NT",
  ),
  make(
    60,
    "2PE",
    "2 Peter",
    "2 பேதுரு",
    3,
    ["2pe", "2 pet", "2pet", "2 pe", "2p", "2 pethuru", "2pethuru", "2 பேது"],
    "NT",
  ),
  make(
    61,
    "1JN",
    "1 John",
    "1 யோவான்",
    5,
    ["1jn", "1 jn", "1 john", "1jo", "1 jo", "1 yovan", "1yovan", "1 யோவா", "1 யோ"],
    "NT",
  ),
  make(
    62,
    "2JN",
    "2 John",
    "2 யோவான்",
    1,
    ["2jn", "2 jn", "2 john", "2jo", "2 yovan", "2yovan", "2 யோவா", "2 யோ"],
    "NT",
  ),
  make(
    63,
    "3JN",
    "3 John",
    "3 யோவான்",
    1,
    ["3jn", "3 jn", "3 john", "3jo", "3 yovan", "3yovan", "3 யோவா", "3 யோ"],
    "NT",
  ),
  make(64, "JUD", "Jude", "யூதா", 1, ["jud", "jude", "yutha", "யூதா"], "NT"),
  make(
    65,
    "REV",
    "Revelation",
    "வெளிப்படுத்தின விசேஷம்",
    22,
    [
      "rev",
      "re",
      "rv",
      "apoc",
      "revelation",
      "velipaduthina",
      "velippaduthina",
      "velipaduthina visesham",
      "வெளி",
      "வெளிப்",
      "வெளிப்படுத்தின",
    ],
    "NT",
  ),
];

export function bookByIndex(i: number): BibleBookMeta | undefined {
  return BIBLE_BOOKS[i];
}
