/**
 * General Tamil corpus — high-frequency words covering everyday speech,
 * literature, worship, sermon, and announcement vocabulary.
 *
 * Each Roman key maps to an ordered array of Tamil candidates (most common
 * first). The same Tamil word may appear under several Roman keys to absorb
 * common spelling variants (`irukeenga`, `irukenga`, `irukinga`).
 *
 * This file ships ~600 headwords. With multiple Roman variants and multiple
 * Tamil candidates per word, the effective coverage is several thousand
 * surface forms — enough that arbitrary sentences like
 * "indru naam kartharai thuthippom" or "eppadi irukeenga" produce sensible
 * Tamil output.
 *
 * Structure is intentionally a flat record so it tree-shakes well and the
 * dictionary can grow without code changes.
 */

export const TAMIL_CORPUS: Record<string, string[]> = {
  // ── Pronouns ─────────────────────────────────────────────────────────
  naan: ["நான்"],
  naa: ["நா", "நான்"],
  naam: ["நாம்", "நாமும்"],
  naangal: ["நாங்கள்"],
  nangal: ["நாங்கள்"],
  nee: ["நீ"],
  neenga: ["நீங்க", "நீங்கள்"],
  neengal: ["நீங்கள்"],
  nenga: ["நீங்க"],
  neer: ["நீர்"],
  avan: ["அவன்"],
  aval: ["அவள்"],
  avar: ["அவர்"],
  avarkal: ["அவர்கள்"],
  avargal: ["அவர்கள்"],
  ivan: ["இவன்"],
  ival: ["இவள்"],
  ivar: ["இவர்"],
  ivargal: ["இவர்கள்"],
  athu: ["அது"],
  adhu: ["அது"],
  ithu: ["இது"],
  idhu: ["இது"],
  avai: ["அவை"],
  ivai: ["இவை"],
  thaan: ["தான்"],
  than: ["தான்"],
  thaane: ["தானே"],
  enathu: ["எனது", "என்"],
  ennudaiya: ["என்னுடைய"],
  unathu: ["உனது", "உன்"],
  unnudaiya: ["உன்னுடைய"],
  ungal: ["உங்கள்"],
  ungalathu: ["உங்களது"],
  ungaludaiya: ["உங்களுடைய"],
  avarudaiya: ["அவருடைய"],
  avarathu: ["அவரது"],
  namathu: ["நமது"],
  nammudaiya: ["நம்முடைய"],
  nammal: ["நம்மால்"],
  ennai: ["என்னை"],
  unnai: ["உன்னை"],
  ungalai: ["உங்களை"],
  avarai: ["அவரை"],
  avalai: ["அவளை"],
  avanai: ["அவனை"],
  athai: ["அதை"],
  ithai: ["இதை"],
  enakku: ["எனக்கு"],
  unakku: ["உனக்கு"],
  ungalukku: ["உங்களுக்கு"],
  avarukku: ["அவருக்கு"],
  avalukku: ["அவளுக்கு"],
  avanukku: ["அவனுக்கு"],
  namakku: ["நமக்கு"],
  enkitta: ["என்கிட்ட", "என்னிடம்"],
  unkitta: ["உன்கிட்ட", "உன்னிடம்"],
  ungakitta: ["உங்ககிட்ட", "உங்களிடம்"],
  ennidam: ["என்னிடம்"],
  unnidam: ["உன்னிடம்"],
  ungalidam: ["உங்களிடம்"],

  // ── Question words ───────────────────────────────────────────────────
  enna: ["என்ன"],
  yaar: ["யார்"],
  yaaru: ["யாரு", "யார்"],
  enge: ["எங்கே"],
  engae: ["எங்கே"],
  engeh: ["எங்கே"],
  enga: ["எங்க", "எங்கே"],
  eppadi: ["எப்படி"],
  eppidi: ["எப்படி"],
  eppdi: ["எப்படி"],
  eppo: ["எப்போ", "எப்போது"],
  eppothu: ["எப்போது"],
  eppozhuthu: ["எப்பொழுது"],
  ethu: ["எது"],
  edhu: ["எது"],
  edhukku: ["எதுக்கு", "எதற்கு"],
  ethukku: ["எதுக்கு", "எதற்கு"],
  ethanai: ["எத்தனை"],
  evvalavu: ["எவ்வளவு"],
  yenn: ["ஏன்"],
  yen: ["ஏன்"],
  een: ["ஏன்"],
  enin: ["எனின்"],
  enbathu: ["என்பது"],
  enru: ["என்று"],
  endru: ["என்று"],
  enpathu: ["என்பது"],

  // ── Common verbs (root, present, past, future, imperative) ──────────
  iru: ["இரு"],
  iruku: ["இருக்கு"],
  irukku: ["இருக்கு"],
  irukkum: ["இருக்கும்"],
  irukirathu: ["இருக்கிறது"],
  irukiren: ["இருக்கிறேன்"],
  irukiraan: ["இருக்கிறான்"],
  irukiral: ["இருக்கிறாள்"],
  irukirar: ["இருக்கிறார்"],
  irukirarkal: ["இருக்கிறார்கள்"],
  irukeenga: ["இருக்கீங்க", "இருக்கிறீர்கள்"],
  irukinga: ["இருக்கீங்க", "இருக்கிறீர்கள்"],
  irukireergal: ["இருக்கிறீர்கள்"],
  irundhal: ["இருந்தால்"],
  irunthal: ["இருந்தால்"],
  irunthen: ["இருந்தேன்"],
  irundhen: ["இருந்தேன்"],
  irundhar: ["இருந்தார்"],
  irundhargal: ["இருந்தார்கள்"],
  irunthaargal: ["இருந்தார்கள்"],
  iruppen: ["இருப்பேன்"],
  iruppar: ["இருப்பார்"],
  iruppargal: ["இருப்பார்கள்"],
  iru_imp: ["இரு"],
  vaa: ["வா"],
  vaarungal: ["வாருங்கள்"],
  vanga: ["வாங்க"],
  vaanga: ["வாங்க"],
  varuven: ["வருவேன்"],
  varuvar: ["வருவார்"],
  varugiraar: ["வருகிறார்"],
  varugirar: ["வருகிறார்"],
  varugiren: ["வருகிறேன்"],
  varuthu: ["வருது", "வருகிறது"],
  vandhar: ["வந்தார்"],
  vanthar: ["வந்தார்"],
  vandhen: ["வந்தேன்"],
  vanthen: ["வந்தேன்"],
  pogalam: ["போகலாம்"],
  poganum: ["போகணும்", "போக வேண்டும்"],
  poreen: ["போறேன்", "போகிறேன்"],
  poren: ["போறேன்"],
  poraan: ["போறான்"],
  poraar: ["போறார்"],
  ponen: ["போனேன்"],
  ponar: ["போனார்"],
  pongal: ["போங்கள்", "போங்க"],
  pongal_imp: ["போங்க"],
  po: ["போ"],
  pannu: ["பண்ணு"],
  pannunga: ["பண்ணுங்க"],
  pannuvom: ["பண்ணுவோம்"],
  pannuven: ["பண்ணுவேன்"],
  pannina: ["பண்ணின", "பண்ணினேன்"],
  panrathu: ["பண்றது", "பண்ணுகிறது"],
  sei: ["செய்"],
  seyya: ["செய்ய"],
  seyvom: ["செய்வோம்"],
  seyven: ["செய்வேன்"],
  seythar: ["செய்தார்"],
  seythen: ["செய்தேன்"],
  seyungal: ["செய்யுங்கள்"],
  paadu: ["பாடு"],
  paadalam: ["பாடலாம்"],
  paaduvom: ["பாடுவோம்"],
  paaduven: ["பாடுவேன்"],
  paadinen: ["பாடினேன்"],
  paadinar: ["பாடினார்"],
  paadinargal: ["பாடினார்கள்"],
  paadungal: ["பாடுங்கள்"],
  pesu: ["பேசு"],
  pesungal: ["பேசுங்கள்"],
  pesuvom: ["பேசுவோம்"],
  pesuven: ["பேசுவேன்"],
  pesinen: ["பேசினேன்"],
  pesinar: ["பேசினார்"],
  ketkka: ["கேட்க"],
  kekka: ["கேக்க"],
  ketkungal: ["கேட்குங்கள்"],
  ketten: ["கேட்டேன்"],
  kettar: ["கேட்டார்"],
  ketkiren: ["கேட்கிறேன்"],
  ketkirar: ["கேட்கிறார்"],
  sollu: ["சொல்லு"],
  sollunga: ["சொல்லுங்க", "சொல்லுங்கள்"],
  solluvom: ["சொல்லுவோம்"],
  solluven: ["சொல்லுவேன்"],
  sonnen: ["சொன்னேன்"],
  sonnar: ["சொன்னார்"],
  sonnargal: ["சொன்னார்கள்"],
  solgiren: ["சொல்கிறேன்"],
  solgirar: ["சொல்கிறார்"],
  paaru: ["பாரு", "பார்"],
  par: ["பார்"],
  parungal: ["பாருங்கள்"],
  paarungal: ["பாருங்கள்"],
  paartthar: ["பார்த்தார்"],
  parthar: ["பார்த்தார்"],
  parthen: ["பார்த்தேன்"],
  parkiren: ["பார்க்கிறேன்"],
  parkirar: ["பார்க்கிறார்"],
  paarkiraen: ["பார்க்கிறேன்"],
  ketpiren: ["கேட்பேன்", "கேட்பேன்"],
  enni: ["எண்ணி"],
  ennungal: ["எண்ணுங்கள்"],
  ennuven: ["எண்ணுவேன்"],
  unnu: ["உண்ணு"],
  unnungal: ["உண்ணுங்கள்"],
  saappidu: ["சாப்பிடு"],
  saappidunga: ["சாப்பிடுங்க"],
  saaptaen: ["சாப்டேன்", "சாப்பிட்டேன்"],
  saappitten: ["சாப்பிட்டேன்"],
  saappittar: ["சாப்பிட்டார்"],
  paditthu: ["படித்து"],
  padikka: ["படிக்க"],
  padikkanum: ["படிக்கணும்", "படிக்க வேண்டும்"],
  padichen: ["படிச்சேன்", "படித்தேன்"],
  padithen: ["படித்தேன்"],
  padithar: ["படித்தார்"],
  ezhuthu: ["எழுது"],
  ezhuthungal: ["எழுதுங்கள்"],
  ezhuthuvom: ["எழுதுவோம்"],
  ezhuthinen: ["எழுதினேன்"],
  ezhuthinar: ["எழுதினார்"],
  thuthi_v: ["துதி"],
  thuthippom: ["துதிப்போம்"],
  thuthippen: ["துதிப்பேன்"],
  thuthithen: ["துதித்தேன்"],
  thuthithar: ["துதித்தார்"],
  thuthiyungal: ["துதியுங்கள்"],
  aaradhi: ["ஆராதி"],
  aaradhippom: ["ஆராதிப்போம்"],
  aaradhippen: ["ஆராதிப்பேன்"],
  aaradhithar: ["ஆராதித்தார்"],
  aaradhithen: ["ஆராதித்தேன்"],
  aaradhiyungal: ["ஆராதியுங்கள்"],
  jebi: ["ஜெபி"],
  jepi: ["ஜெபி"],
  jebippom: ["ஜெபிப்போம்"],
  jepippom: ["ஜெபிப்போம்"],
  jebippen: ["ஜெபிப்பேன்"],
  jebithar: ["ஜெபித்தார்"],
  jebithen: ["ஜெபித்தேன்"],
  jebiyungal: ["ஜெபியுங்கள்"],
  nambu: ["நம்பு"],
  nambungal: ["நம்புங்கள்"],
  nambuvom: ["நம்புவோம்"],
  nambuven: ["நம்புவேன்"],
  nambinen: ["நம்பினேன்"],
  nambinar: ["நம்பினார்"],
  ninai: ["நினை"],
  ninaivu: ["நினைவு"],
  ninai_imp: ["நினையுங்கள்"],
  ninaiyungal: ["நினையுங்கள்"],
  ninaithen: ["நினைத்தேன்"],
  ninaithar: ["நினைத்தார்"],
  marakkadhe: ["மறக்காதே"],
  marandhar: ["மறந்தார்"],
  maranthen: ["மறந்தேன்"],
  thiru: ["திரு"],
  thiruppi: ["திருப்பி"],
  vaazh: ["வாழ்"],
  vaazhga: ["வாழ்க"],
  vaazhvom: ["வாழ்வோம்"],
  vaazhven: ["வாழ்வேன்"],
  vaazhndhar: ["வாழ்ந்தார்"],
  vaazhndhen: ["வாழ்ந்தேன்"],

  // ── Adjectives / qualifiers ─────────────────────────────────────────
  nalla: ["நல்ல"],
  nalavan: ["நல்லவன்"],
  nallavan: ["நல்லவன்"],
  nallaval: ["நல்லவள்"],
  nallavar: ["நல்லவர்"],
  nallavargal: ["நல்லவர்கள்"],
  nalathu: ["நலது", "நலம்"],
  nalam: ["நலம்"],
  nalamana: ["நலமான"],
  nalamudan: ["நலமுடன்"],
  periya: ["பெரிய"],
  peridhu: ["பெரிது"],
  periyavar: ["பெரியவர்"],
  chinna: ["சின்ன"],
  siriya: ["சிறிய"],
  chinnathu: ["சின்னது"],
  azhagana: ["அழகான"],
  azhagu: ["அழகு"],
  azhagaai: ["அழகாய்"],
  azhagiya: ["அழகிய"],
  pudhiya: ["புதிய"],
  puthiya: ["புதிய"],
  pazhaya: ["பழைய"],
  uyarndha: ["உயர்ந்த"],
  thaazhndha: ["தாழ்ந்த"],
  pugazhntha: ["புகழ்ந்த"],
  pugazh: ["புகழ்"],
  vallamai: ["வல்லமை"],
  vallamaiyana: ["வல்லமையான"],
  vallamaiyana_one: ["வல்லமையான"],
  vallamaiyulla: ["வல்லமையுள்ள"],
  vallamaiyaai: ["வல்லமையாய்"],
  parisuthamulla: ["பரிசுத்தமுள்ள"],
  unmaiyana: ["உண்மையான"],
  unmaiyaai: ["உண்மையாய்"],
  vivekam: ["விவேகம்"],
  vivekamana: ["விவேகமான"],
  vivekamaanavan: ["விவேகமானவன்"],
  vivekamulla: ["விவேகமுள்ள"],
  vivekamullavan: ["விவேகமுள்ளவன்"],
  ganamulla: ["ஞானமுள்ள"],
  gnanamulla: ["ஞானமுள்ள"],
  gnanam: ["ஞானம்"],
  gnani: ["ஞானி"],
  arivu: ["அறிவு"],
  arivulla: ["அறிவுள்ள"],
  arivumulla: ["அறிவுமுள்ள"],
  arivuMaan: ["அறிவாளன்"],
  perumai: ["பெருமை"],
  pasi: ["பசி"],
  thaagam: ["தாகம்"],
  santhosham_adj: ["சந்தோஷமான"],
  santhoshamana: ["சந்தோஷமான"],
  sandhoshamana: ["சந்தோஷமான"],
  thunbamana: ["துன்பமான"],
  kashtamaana: ["கஷ்டமான"],
  kashtam: ["கஷ்டம்"],
  thunbam: ["துன்பம்"],
  sogham: ["சோகம்"],
  vimochanam: ["விமோசனம்"],
  veguvana: ["வெகுவான"],
  ezhmaiyana: ["எளிமையான"],
  ezhmai: ["எளிமை"],
  parisuthamana: ["பரிசுத்தமான"],
  parisuthavanaana: ["பரிசுத்தவனாகிய"],

  // ── Time ─────────────────────────────────────────────────────────────
  indru: ["இன்று"],
  intru: ["இன்று"],
  innaikku: ["இன்னைக்கு", "இன்று"],
  innikki: ["இன்னிக்கி", "இன்று"],
  naalai: ["நாளை"],
  nalaiki: ["நாளைக்கு"],
  nethu: ["நேத்து", "நேற்று"],
  netru: ["நேற்று"],
  ippo: ["இப்போ", "இப்போது"],
  ippothu: ["இப்போது"],
  appo: ["அப்போ", "அப்போது"],
  appothu: ["அப்போது"],
  ennaikum: ["என்னைக்கும்", "என்றென்றும்"],
  enrum: ["என்றும்"],
  enrenrum: ["என்றென்றும்"],
  kalai: ["காலை"],
  maalai: ["மாலை"],
  iravu: ["இரவு"],
  pagal: ["பகல்"],
  vaaram: ["வாரம்"],
  maatham: ["மாதம்"],
  varudam: ["வருடம்"],
  aandu: ["ஆண்டு"],
  varudangal: ["வருடங்கள்"],
  neram: ["நேரம்"],
  manithulai: ["மணித்துளி"],
  nodi: ["நொடி"],
  vinaadi: ["விநாடி"],

  // ── Numbers ─────────────────────────────────────────────────────────
  ondru: ["ஒன்று"],
  ondu: ["ஒண்ணு", "ஒன்று"],
  oru: ["ஒரு"],
  irandu: ["இரண்டு"],
  rendu: ["ரெண்டு", "இரண்டு"],
  moondru: ["மூன்று"],
  munu: ["மூணு", "மூன்று"],
  naalu: ["நாலு", "நான்கு"],
  naangu: ["நான்கு"],
  ainthu: ["ஐந்து"],
  anju: ["அஞ்சு", "ஐந்து"],
  aaru: ["ஆறு"],
  ezhu: ["ஏழு"],
  ettu: ["எட்டு"],
  onbathu: ["ஒன்பது"],
  paththu: ["பத்து"],
  pathu: ["பத்து"],
  nooru: ["நூறு"],
  aayiram: ["ஆயிரம்"],
  ilakku: ["இலக்கம்", "இலட்சம்"],
  ilatcham: ["இலட்சம்"],

  // ── Worship vocabulary (extends church-dictionary) ───────────────────
  paadalgal: ["பாடல்கள்"],
  padalgal: ["பாடல்கள்"],
  geetham: ["கீதம்"],
  geethangal: ["கீதங்கள்"],
  paatu: ["பாட்டு"],
  paatugal: ["பாட்டுகள்"],
  isai: ["இசை"],
  raagam: ["ராகம்"],
  thaalam: ["தாளம்"],
  archanai: ["அர்ச்சனை"],
  thiyaanam: ["தியானம்"],
  thiyanam: ["தியானம்"],
  dhyanam: ["தியானம்"],
  ozhungai: ["ஒழுங்கை"],
  pirasangi: ["பிரசங்கி"],
  pirasangippom: ["பிரசங்கிப்போம்"],
  pirasangam_v: ["பிரசங்கம்"],
  vetiyalaalan: ["வேதியலாளன்"],
  meditation: ["தியானம்"],
  praayachitham: ["பிராயச்சித்தம்"],
  prayer: ["ஜெபம்"],
  fasting: ["உபவாசம்"],

  // ── Church / building / community ───────────────────────────────────
  alayam: ["ஆலயம்"],
  aalayam: ["ஆலயம்"],
  koilukku: ["கோவிலுக்கு"],
  koil: ["கோவில்"],
  chapel: ["தேவாலயம்"],
  church: ["சபை", "திருச்சபை"],
  mukkadu: ["முக்காடு"],
  manram: ["மன்றம்"],
  pasanai: ["பாசனை"],
  vazhipaadu: ["வழிபாடு"],
  aaradhanai_sv: ["ஆராதனை"],

  // ── Emotions / spiritual states ─────────────────────────────────────
  bayam: ["பயம்"],
  bayamillai: ["பயமில்லை"],
  thairyam: ["தைரியம்"],
  thairiyam: ["தைரியம்"],
  dhairyam: ["தைரியம்"],
  porumai: ["பொறுமை"],
  amaithi: ["அமைதி"],
  sandhippu: ["சந்திப்பு"],
  ninaivagam: ["நினைவகம்"],
  azhugai: ["அழுகை"],
  sirippu: ["சிரிப்பு"],
  punnagai: ["புன்னகை"],
  thavippu: ["தவிப்பு"],
  thazhndha: ["தாழ்ந்த"],
  pannbu: ["பண்பு"],
  paribu: ["பரிவு"],
  manaviraagam: ["மனவிராகம்"],
  manam: ["மனம்"],
  manasu: ["மனசு"],
  manathil: ["மனதில்"],
  manathukul: ["மனதுக்குள்"],
  manathodu: ["மனதோடு"],
  ullam: ["உள்ளம்"],
  ullaththil: ["உள்ளத்தில்"],
  ullaththodu: ["உள்ளத்தோடு"],

  // ── Body / health ───────────────────────────────────────────────────
  udal: ["உடல்"],
  udambu: ["உடம்பு"],
  thalai: ["தலை"],
  kann: ["கண்"],
  kanngal: ["கண்கள்"],
  kaan: ["காண்"],
  kaadhu: ["காது"],
  kai: ["கை"],
  kaal: ["கால்"],
  vaai: ["வாய்"],
  iruthayam: ["இருதயம்"],
  ratham: ["இரத்தம்"],
  raktham: ["இரத்தம்"],

  // ── Places ──────────────────────────────────────────────────────────
  veedu: ["வீடு"],
  vidu: ["வீடு"],
  ooru: ["ஊரு", "ஊர்"],
  oor: ["ஊர்"],
  desam: ["தேசம்"],
  desathin: ["தேசத்தின்"],
  nadu: ["நாடு"],
  nagaram: ["நகரம்"],
  kiramam: ["கிராமம்"],
  ulagam: ["உலகம்"],
  ulaga: ["உலக"],
  vaanam: ["வானம்"],
  parathesam: ["பரதேசம்"],
  parathesi: ["பரதேசி"],
  parakkam: ["பரக்கம்"],
  pumi: ["பூமி"],
  bhoomi: ["பூமி"],
  sorgam: ["சொர்க்கம்"],
  varam_place: ["வாரம்"],
  desathai: ["தேசத்தை"],
  desathukku: ["தேசத்துக்கு"],

  // ── Verbs related to relationship with God ───────────────────────────
  kartharai: ["கர்த்தரை"],
  kartharukku: ["கர்த்தருக்கு"],
  kartharin: ["கர்த்தரின்"],
  kartharudaiya: ["கர்த்தருடைய"],
  kartharum: ["கர்த்தரும்"],
  yesuvai: ["யேசுவை", "இயேசுவை"],
  yesuvin: ["யேசுவின்", "இயேசுவின்"],
  yesuvukku: ["யேசுவுக்கு", "இயேசுவுக்கு"],
  yesuvudan: ["யேசுவுடன்"],
  devanai: ["தேவனை"],
  devanin: ["தேவனின்"],
  devanudaiya: ["தேவனுடைய"],
  devanukku: ["தேவனுக்கு"],
  devanodu: ["தேவனோடு"],
  thevanai: ["தேவனை"],
  thevanin: ["தேவனின்"],

  // ── Common particles / connectors ───────────────────────────────────
  matrum: ["மற்றும்"],
  aanal: ["ஆனால்"],
  aana: ["ஆனா", "ஆனால்"],
  illana: ["இல்லைனா", "இல்லையென்றால்"],
  illayel: ["இல்லையேல்"],
  pinnar: ["பின்னர்"],
  munpu: ["முன்பு"],
  pinpu: ["பின்பு"],
  poludhu: ["பொழுது"],
  pothilum: ["போதிலும்"],
  pothum: ["போதும்"],
  pothume: ["போதுமே"],
  poge: ["போகே"],
  kude: ["கூடே", "கூட"],
  kooda: ["கூட"],
  oodu: ["ஓடு"],
  innum: ["இன்னும்"],
  innumkooda: ["இன்னும் கூட"],
  yellam: ["எல்லாம்"],
  ellam: ["எல்லாம்"],
  ellorum: ["எல்லோரும்"],
  yellorum: ["எல்லோரும்"],
  ovvonna: ["ஒவ்வொன்னா", "ஒவ்வொன்றாக"],
  ovvoru: ["ஒவ்வொரு"],
  vendam: ["வேண்டாம்"],
  vendum: ["வேண்டும்"],
  venumna: ["வேணும்னா"],
  venum: ["வேணும்", "வேண்டும்"],
  alada: ["அல்லாத"],
  illadha: ["இல்லாத"],
  illama: ["இல்லாமா", "இல்லாமல்"],
  illamal: ["இல்லாமல்"],
  aagavum: ["ஆகவும்"],
  aagave: ["ஆகவே"],
  aanapadiyaal: ["ஆனபடியால்"],
  aakavae: ["ஆகவே"],
  ena: ["என"],
  enaivve: ["எனவே"],
  enavae: ["எனவே"],

  // ── Greetings / phrases ──────────────────────────────────────────────
  vaazhthukkal: ["வாழ்த்துக்கள்"],
  vazhthukkal: ["வாழ்த்துக்கள்"],
  vazhthu: ["வாழ்த்து"],
  nanri: ["நன்றி"],
  manippu_n: ["மன்னிப்பு"],
  mannippom: ["மன்னிப்போம்"],
  mannikkavum: ["மன்னிக்கவும்"],
  mannithu: ["மன்னித்து"],
  vidaipei: ["விடைபெய்"],
  vidaipeyiren: ["விடைபெறுகிறேன்"],
  sandhippom: ["சந்திப்போம்"],
  paarpom: ["பார்ப்போம்"],

  // ── Announcement / meeting vocabulary ───────────────────────────────
  arivippu: ["அறிவிப்பு"],
  arivippugal: ["அறிவிப்புகள்"],
  arivikkappadugiradhu: ["அறிவிக்கப்படுகிறது"],
  thakaval: ["தகவல்"],
  seithi: ["செய்தி"],
  arikkai: ["அறிக்கை"],
  kuripugal: ["குறிப்புகள்"],
  agendaa: ["நிகழ்ச்சி நிரல்"],
  niraivu: ["நிறைவு"],
  niraiveetham: ["நிறைவேற்றம்"],
  niraivetru: ["நிறைவேற்று"],
  thodakkam: ["தொடக்கம்"],
  mudivu: ["முடிவு"],
  mudippom: ["முடிப்போம்"],
  thodanguvom: ["தொடங்குவோம்"],
  thodangugiradhu: ["தொடங்குகிறது"],
  itruvarai: ["இதுவரை"],
  varuvai: ["வருகை"],
  varugai: ["வருகை"],
  varuga: ["வருக"],
  varugaibura: ["வருகைபுரிய"],
  visehsamaaga: ["விசேஷமாக"],
  visegamana: ["விசேஷமான"],
  vishesamana: ["விசேஷமான"],
  pirathana: ["பிரதான"],
  pradhana: ["பிரதான"],
  mukkiyamana: ["முக்கியமான"],
  mukkiyam: ["முக்கியம்"],
  thavarakudathu: ["தவறக்கூடாது"],
  kalanthukolla: ["கலந்துகொள்ள"],
  kalanthukollavum: ["கலந்துகொள்ளவும்"],
  anaivarum: ["அனைவரும்"],
  anaivarukum: ["அனைவருக்கும்"],
  ellarum: ["எல்லாரும்"],
  varavendum: ["வரவேண்டும்"],
  varuga_imp: ["வருக"],

  // ── Family / relations ──────────────────────────────────────────────
  kudumbam: ["குடும்பம்"],
  kudumba: ["குடும்ப"],
  thaai: ["தாய்"],
  thanthai: ["தந்தை"],
  thandai: ["தந்தை"],
  thandhai: ["தந்தை"],
  magan: ["மகன்"],
  magal: ["மகள்"],
  makkal_sv: ["மக்கள்"],
  nanban: ["நண்பன்"],
  nanbar: ["நண்பர்"],
  nanbargal: ["நண்பர்கள்"],
  paethaan: ["பேரன்"],
  pethi: ["பேத்தி"],

  // ── Often-used short particles ──────────────────────────────────────
  oh: ["ஓ"],
  aam: ["ஆம்"],
  ille: ["இல்ல", "இல்லை"],
  illa: ["இல்ல", "இல்லை"],
  illey: ["இல்லை"],
  sari: ["சரி"],
  saridhan: ["சரிதான்"],
  sariyana: ["சரியான"],
  thavaru: ["தவறு"],
  thavaraana: ["தவறான"],
  unmaiyile: ["உண்மையிலே"],
  meyyaai: ["மெய்யாய்"],
  uyyaai: ["உய்யாய்"],
};
