import type { AppSettings } from "@/db/schema";
import {
  Settings, Palette, MonitorPlay, Type, Sparkles, BookOpen, Music,
  Image, Search, Zap, Volume2, Video, Keyboard, Wifi, Download,
  HardDrive, Shield, Sliders, Info, type LucideIcon,
} from "lucide-react";

export interface SettingDef {
  key: keyof AppSettings;
  title: string;
  description: string;
  keywords: string[];
  aliases: string[];
  tags: string[];
  type: "toggle" | "slider" | "select" | "input" | "color" | "number";
  category: string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  placeholder?: string;
}

const ALL: SettingDef[] = [
  // ════════════════════ General ════════════════════
  { key: "theme", title: "Theme", description: "Switch between light, dark, or system theme", keywords: ["dark mode", "light mode", "system", "appearance", "color scheme", "night", "day"], aliases: ["color-theme", "ui-theme"], tags: ["appearance", "visual", "mode"], type: "select", category: "general", options: [{ value: "light", label: "Light" }, { value: "dark", label: "Dark" }, { value: "system", label: "System" }] },
  { key: "accentColor", title: "Accent Color", description: "Primary brand color used throughout the interface", keywords: ["primary", "brand", "highlight", "theme color", "ui color"], aliases: ["primary-color", "brand-color"], tags: ["color", "appearance", "brand"], type: "color", category: "general" },
  { key: "language", title: "Language", description: "UI display language for the application interface", keywords: ["locale", "i18n", "region", "translation", "internationalization"], aliases: ["locale", "ui-language"], tags: ["region", "international"], type: "select", category: "general", options: [{ value: "en", label: "English" }] },
  { key: "autoSave", title: "Auto Save", description: "Automatically save changes as you work", keywords: ["save", "persist", "automatic", "backup", "write"], aliases: ["autosave", "save-automatically"], tags: ["save", "persistence"], type: "toggle", category: "general" },
  { key: "startupBehavior", title: "Startup Behavior", description: "What to show when the application launches", keywords: ["launch", "boot", "start", "restore", "session", "welcome"], aliases: ["launch-behavior", "on-startup"], tags: ["launch", "startup", "boot"], type: "select", category: "general", options: [{ value: "restore", label: "Restore Last Session" }, { value: "new", label: "Start Fresh" }, { value: "blank", label: "Blank Workspace" }] },
  { key: "checkUpdates", title: "Check for Updates", description: "Automatically check for new versions on startup", keywords: ["updates", "version", "upgrade", "new release", "auto-update", "latest"], aliases: ["auto-update", "update-check"], tags: ["updates", "version"], type: "toggle", category: "general" },
  { key: "autoLaunch", title: "Launch at System Startup", description: "Start the application when your computer boots", keywords: ["boot", "startup", "auto-start", "system", "login", "autostart"], aliases: ["auto-start", "open-at-login"], tags: ["startup", "system"], type: "toggle", category: "general" },
  { key: "recentProjects", title: "Recent Projects Limit", description: "Number of recent projects to remember in the history list", keywords: ["recent", "history", "projects", "limit", "max", "count"], aliases: ["recent-count", "max-recent"], tags: ["projects", "history"], type: "number", category: "general", min: 0, max: 50 },
  { key: "defaultStartupPage", title: "Default Startup Page", description: "Page to show when the application launches", keywords: ["start", "home", "landing", "default page", "launch", "welcome"], aliases: ["home-page", "start-page"], tags: ["startup", "navigation"], type: "select", category: "general", options: [{ value: "library", label: "Library" }, { value: "project", label: "Project" }, { value: "playlists", label: "Playlists" }, { value: "settings", label: "Settings" }] },
  { key: "telemetry", title: "Telemetry", description: "Share anonymous usage data to help improve the application", keywords: ["analytics", "usage", "data", "privacy", "anonymous", "statistics"], aliases: ["usage-data", "analytics"], tags: ["privacy", "data"], type: "toggle", category: "general" },

  // ════════════════════ Appearance ════════════════════
  { key: "compactMode", title: "Compact Mode", description: "Tighter spacing for more content on screen", keywords: ["density", "spacing", "compact", "tight", "small", "padding", "cramped"], aliases: ["compact-ui", "dense"], tags: ["layout", "density"], type: "toggle", category: "appearance" },
  { key: "sidebarWidth", title: "Sidebar Width", description: "Width of the navigation sidebar in pixels", keywords: ["sidebar", "nav", "panel", "width", "size", "navigation"], aliases: ["nav-width", "sidebar-size"], tags: ["layout", "sidebar", "navigation"], type: "slider", category: "appearance", min: 180, max: 320, unit: "px" },
  { key: "uiScale", title: "UI Scale", description: "Scale the entire user interface", keywords: ["zoom", "size", "scaling", "dpi", "magnification", "display"], aliases: ["zoom-level", "display-scale"], tags: ["accessibility", "display"], type: "slider", category: "appearance", min: 75, max: 150, step: 5, unit: "%" },
  { key: "iconSize", title: "Icon Size", description: "Size of toolbar and navigation icons in pixels", keywords: ["icons", "size", "toolbar", "symbols"], aliases: ["icon-scale", "toolbar-icons"], tags: ["icons", "toolbar"], type: "slider", category: "appearance", min: 12, max: 24, unit: "px" },
  { key: "blurEffects", title: "Blur Effects", description: "Enable backdrop blur on modals and panels", keywords: ["blur", "glass", "frosted", "transparency", "effects", "backdrop", "acrylic"], aliases: ["backdrop-blur", "frosted-glass"], tags: ["effects", "visual"], type: "toggle", category: "appearance" },
  { key: "glassEffects", title: "Glass Effects", description: "Frosted glass appearance on panels and surfaces", keywords: ["glass", "frosted", "translucent", "transparency", "effects", "acrylic", "mica"], aliases: ["acrylic", "mica"], tags: ["effects", "visual"], type: "toggle", category: "appearance" },
  { key: "animationsEnabled", title: "Animations", description: "Enable UI animations throughout the interface", keywords: ["animation", "motion", "effects", "transitions", "animate"], aliases: ["enable-motion", "ui-animations"], tags: ["motion", "effects"], type: "toggle", category: "appearance" },
  { key: "reduceMotion", title: "Reduce Motion", description: "Minimize animations for accessibility", keywords: ["motion", "accessibility", "animation", "prefers-reduced-motion", "epilepsy"], aliases: ["reduced-motion", "prefer-no-motion"], tags: ["accessibility", "motion"], type: "toggle", category: "appearance" },
  { key: "roundedCorners", title: "Rounded Corners", description: "Border radius for UI elements", keywords: ["radius", "rounded", "corners", "border", "curved", "pill"], aliases: ["border-radius", "corner-radius"], tags: ["appearance", "shape"], type: "slider", category: "appearance", min: 0, max: 24, unit: "px" },
  { key: "blurStrength", title: "Blur Strength", description: "Intensity of backdrop blur effects", keywords: ["blur", "strength", "intensity", "backdrop", "glass", "frost"], aliases: ["blur-intensity", "glass-blur"], tags: ["effects", "visual"], type: "slider", category: "appearance", min: 0, max: 200, step: 10, unit: "%" },
  { key: "accentOpacity", title: "Accent Opacity", description: "Transparency level of accent color overlays", keywords: ["accent", "opacity", "transparency", "alpha", "overlay"], aliases: ["accent-alpha", "primary-opacity"], tags: ["color", "appearance"], type: "slider", category: "appearance", min: 0, max: 100, step: 5, unit: "%" },
  { key: "scrollbarStyle", title: "Scrollbar Style", description: "Visual style of scrollbars throughout the application", keywords: ["scrollbar", "scroll", "thin", "hidden", "auto", "style"], aliases: ["scroll-style", "scrollbar-visibility"], tags: ["scroll", "appearance"], type: "select", category: "appearance", options: [{ value: "thin", label: "Thin" }, { value: "auto", label: "Auto" }, { value: "hidden", label: "Hidden" }] },
  { key: "cardRadius", title: "Card Radius", description: "Border radius for cards and containers", keywords: ["card", "radius", "rounded", "container", "panel", "border"], aliases: ["container-radius", "panel-radius"], tags: ["appearance", "shape"], type: "slider", category: "appearance", min: 0, max: 24, unit: "px" },
  { key: "spacing", title: "Spacing", description: "Overall spacing density of the interface", keywords: ["spacing", "density", "compact", "comfortable", "padding", "gap", "layout"], aliases: ["layout-density", "ui-spacing"], tags: ["layout", "density"], type: "select", category: "appearance", options: [{ value: "compact", label: "Compact" }, { value: "normal", label: "Normal" }, { value: "comfortable", label: "Comfortable" }] },

  // ════════════════════ Projection ════════════════════
  { key: "defaultDisplay", title: "Default Display", description: "Name or identifier of the default output display", keywords: ["display", "monitor", "screen", "output", "projector"], aliases: ["output-display", "target-monitor"], tags: ["display", "output"], type: "input", category: "projection", placeholder: "default" },
  { key: "defaultImageDurationMs", title: "Image Duration", description: "Default display duration for still images in seconds", keywords: ["image", "duration", "time", "seconds", "slide", "photo"], aliases: ["image-time", "slide-duration"], tags: ["timing", "media"], type: "number", category: "projection", min: 1, max: 3600, unit: "s" },
  { key: "defaultTransition", title: "Transition Effect", description: "Default transition between projected items", keywords: ["transition", "effect", "animation", "crossfade", "fade", "zoom", "dissolve"], aliases: ["slide-transition", "transition-effect"], tags: ["animation", "transition"], type: "select", category: "projection", options: [{ value: "fade", label: "Fade" }, { value: "crossfade", label: "Crossfade" }, { value: "zoom", label: "Zoom" }, { value: "dissolve", label: "Dissolve" }, { value: "none", label: "None" }] },
  { key: "transitionDuration", title: "Transition Duration", description: "Duration of transitions between projected items in milliseconds", keywords: ["transition", "duration", "speed", "crossfade", "animation", "time"], aliases: ["transition-speed", "animation-duration"], tags: ["animation", "timing"], type: "slider", category: "projection", min: 100, max: 3000, step: 100, unit: "ms" },
  { key: "defaultLoopMode", title: "Loop Mode", description: "Default loop behavior for playlists", keywords: ["loop", "repeat", "cycle", "playlist", "continuous", "auto"], aliases: ["repeat-mode", "loop-playlist"], tags: ["playback", "loop"], type: "select", category: "projection", options: [{ value: "none", label: "No Loop" }, { value: "single", label: "Loop Single" }, { value: "playlist", label: "Loop Playlist" }] },
  { key: "defaultVolume", title: "Default Volume", description: "Starting volume level for media playback", keywords: ["volume", "sound", "audio", "level", "loudness", "gain"], aliases: ["audio-volume", "sound-level"], tags: ["audio", "playback"], type: "slider", category: "projection", min: 0, max: 100, step: 5, unit: "%" },
  { key: "autoplayVideo", title: "Autoplay Videos", description: "Automatically start video playback when selected", keywords: ["video", "autoplay", "play", "media", "auto start"], aliases: ["video-autoplay", "auto-play"], tags: ["playback", "video"], type: "toggle", category: "projection" },
  { key: "muteOnStart", title: "Mute on Start", description: "Start video playback with audio muted", keywords: ["mute", "audio", "sound", "silent", "start", "video"], aliases: ["start-muted", "mute-startup"], tags: ["audio", "playback"], type: "toggle", category: "projection" },
  { key: "projectorResolution", title: "Projector Resolution", description: "Output resolution for the projector window", keywords: ["resolution", "display", "output", "screen", "monitor", "4k", "1080p"], aliases: ["output-resolution", "display-resolution"], tags: ["display", "output"], type: "select", category: "projection", options: [{ value: "1920x1080", label: "1920 × 1080 (Full HD)" }, { value: "3840x2160", label: "3840 × 2160 (4K)" }, { value: "1280x720", label: "1280 × 720 (HD)" }, { value: "1024x768", label: "1024 × 768 (XGA)" }] },
  { key: "safeMargins", title: "Safe Margins", description: "Safe area boundary as percentage of screen", keywords: ["safe", "margin", "boundary", "padding", "area", "overscan", "border"], aliases: ["safe-area", "action-margins"], tags: ["display", "safety"], type: "slider", category: "projection", min: 0, max: 20, unit: "%" },
  { key: "aspectRatio", title: "Aspect Ratio", description: "Display aspect ratio for projection output", keywords: ["aspect", "ratio", "16:9", "4:3", "widescreen", "display"], aliases: ["screen-ratio", "display-aspect"], tags: ["display", "resolution"], type: "select", category: "projection", options: [{ value: "16:9", label: "16:9 (Widescreen)" }, { value: "4:3", label: "4:3 (Standard)" }, { value: "16:10", label: "16:10 (Wide)" }, { value: "21:9", label: "21:9 (Ultrawide)" }] },
  { key: "refreshRate", title: "Refresh Rate", description: "Target refresh rate for the projection output", keywords: ["refresh", "rate", "hz", "fps", "display", "smooth"], aliases: ["display-refresh", "monitor-hz"], tags: ["display", "performance"], type: "select", category: "projection", options: [{ value: "24", label: "24 Hz" }, { value: "30", label: "30 Hz" }, { value: "60", label: "60 Hz" }, { value: "120", label: "120 Hz" }] },
  { key: "fadeDurationMs", title: "Fade Duration", description: "Duration of crossfade transitions between items", keywords: ["fade", "crossfade", "transition", "duration", "speed", "animation"], aliases: ["crossfade-duration", "transition-speed"], tags: ["animation", "timing"], type: "number", category: "projection", min: 100, max: 5000, step: 100, unit: "ms" },
  { key: "defaultBackground", title: "Default Background", description: "Background color shown when no content is projected", keywords: ["background", "color", "default", "empty", "idle", "black"], aliases: ["idle-background", "empty-bg"], tags: ["display", "background"], type: "color", category: "projection" },
  { key: "projectorBrightness", title: "Projector Brightness", description: "Brightness level of the projection output", keywords: ["brightness", "projector", "display", "light", "intensity", "screen"], aliases: ["display-brightness", "screen-brightness"], tags: ["display", "visual"], type: "slider", category: "projection", min: 10, max: 100, step: 5, unit: "%" },
  { key: "blackScreen", title: "Black Screen Between Items", description: "Show a black screen briefly between projected items", keywords: ["black", "screen", "blank", "between", "gap", "interval"], aliases: ["blackout", "blank-between"], tags: ["display", "transition"], type: "toggle", category: "projection" },
  { key: "logoScreen", title: "Logo Screen", description: "Show logo when no content is projected", keywords: ["logo", "brand", "idle", "empty", "placeholder", "splash"], aliases: ["idle-screen", "brand-screen"], tags: ["display", "branding"], type: "toggle", category: "projection" },
  { key: "freezeScreen", title: "Freeze on Idle", description: "Freeze current display when system is idle", keywords: ["freeze", "idle", "pause", "hold", "screen", "inactive"], aliases: ["idle-freeze", "pause-on-idle"], tags: ["display", "idle"], type: "toggle", category: "projection" },
  { key: "countdownSeconds", title: "Countdown Duration", description: "Default countdown timer duration in seconds", keywords: ["countdown", "timer", "seconds", "count", "clock", "duration"], aliases: ["timer-duration", "countdown-time"], tags: ["timing", "countdown"], type: "number", category: "projection", min: 3, max: 300, unit: "s" },
  { key: "autoTransition", title: "Auto Transition", description: "Automatically advance to the next item in a playlist", keywords: ["auto", "transition", "advance", "next", "automatic", "play through"], aliases: ["auto-advance", "autoplay"], tags: ["playback", "automation"], type: "toggle", category: "projection" },

  // ════════════════════ Text Formatting ════════════════════
  { key: "defaultFont", title: "Default Font Family", description: "Primary font for projected text content", keywords: ["font", "typeface", "family", "text", "typography", "type"], aliases: ["font-family", "primary-font"], tags: ["typography", "text"], type: "input", category: "text-formatting", placeholder: "Inter" },
  { key: "fallbackFont", title: "Fallback Font", description: "Secondary font when the primary font is unavailable", keywords: ["font", "fallback", "backup", "secondary", "sans-serif", "serif"], aliases: ["backup-font", "secondary-font"], tags: ["typography", "fallback"], type: "input", category: "text-formatting", placeholder: "sans-serif" },
  { key: "tamilFont", title: "Tamil Font", description: "Font family for Tamil text content", keywords: ["tamil", "font", "tamil font", "tamil text", "language"], aliases: ["tamil-typeface", "ta-font"], tags: ["tamil", "typography", "language"], type: "input", category: "text-formatting", placeholder: "Noto Sans Tamil" },
  { key: "englishFont", title: "English Font", description: "Font family for English text content", keywords: ["english", "font", "english font", "latin", "text"], aliases: ["en-font", "latin-font"], tags: ["english", "typography"], type: "input", category: "text-formatting", placeholder: "Inter" },
  { key: "referenceFont", title: "Reference Font", description: "Font family for Bible reference text", keywords: ["reference", "font", "bible", "verse", "citation"], aliases: ["scripture-font", "verse-font"], tags: ["bible", "typography", "reference"], type: "input", category: "text-formatting", placeholder: "Inter" },
  { key: "fontSize", title: "Font Size", description: "Default font size for projected text in pixels", keywords: ["font", "size", "text", "scale", "large", "small"], aliases: ["text-size", "font-scale"], tags: ["typography", "size"], type: "slider", category: "text-formatting", min: 12, max: 200, unit: "px" },
  { key: "fontWeight", title: "Font Weight", description: "Thickness of text characters", keywords: ["font", "weight", "bold", "thickness", "light", "semibold", "medium"], aliases: ["boldness", "text-weight"], tags: ["typography", "style"], type: "slider", category: "text-formatting", min: 300, max: 900, step: 100 },
  { key: "lineSpacing", title: "Line Spacing", description: "Vertical space between lines of text as a multiplier", keywords: ["line", "spacing", "leading", "height", "vertical", "gap"], aliases: ["line-height", "leading"], tags: ["typography", "spacing"], type: "slider", category: "text-formatting", min: 1, max: 3, step: 0.1 },
  { key: "letterSpacing", title: "Letter Spacing", description: "Horizontal space between characters in pixels", keywords: ["letter", "spacing", "tracking", "kerning", "character", "width"], aliases: ["tracking", "character-spacing"], tags: ["typography", "spacing"], type: "slider", category: "text-formatting", min: -2, max: 8, step: 0.5, unit: "px" },
  { key: "textAlign", title: "Text Alignment", description: "Horizontal alignment of projected text", keywords: ["align", "left", "center", "right", "text", "justify"], aliases: ["text-align", "horizontal-align"], tags: ["typography", "alignment"], type: "select", category: "text-formatting", options: [{ value: "left", label: "Left" }, { value: "center", label: "Center" }, { value: "right", label: "Right" }] },
  { key: "verticalAlign", title: "Vertical Alignment", description: "Vertical alignment of projected text on screen", keywords: ["vertical", "align", "top", "middle", "bottom", "center"], aliases: ["vert-align", "v-align"], tags: ["typography", "alignment"], type: "select", category: "text-formatting", options: [{ value: "top", label: "Top" }, { value: "middle", label: "Middle" }, { value: "bottom", label: "Bottom" }] },
  { key: "textWidth", title: "Text Width", description: "Maximum width of text as percentage of screen", keywords: ["width", "text", "max width", "container", "area"], aliases: ["content-width", "text-container"], tags: ["layout", "text"], type: "slider", category: "text-formatting", min: 30, max: 100, step: 5, unit: "%" },
  { key: "maxWidth", title: "Max Width", description: "Absolute maximum width for text content in pixels", keywords: ["max", "width", "limit", "maximum", "text width"], aliases: ["max-text-width", "width-limit"], tags: ["layout", "text"], type: "number", category: "text-formatting", min: 200, max: 2000, unit: "px" },
  { key: "textMargin", title: "Text Margin", description: "Margin around text content in pixels", keywords: ["margin", "text", "spacing", "padding", "outer"], aliases: ["outer-margin", "text-gap"], tags: ["layout", "spacing"], type: "number", category: "text-formatting", min: 0, max: 200, unit: "px" },
  { key: "textPadding", title: "Text Padding", description: "Padding inside the text container in pixels", keywords: ["padding", "text", "spacing", "margin", "inner"], aliases: ["inner-padding", "text-inset"], tags: ["layout", "spacing"], type: "number", category: "text-formatting", min: 0, max: 200, unit: "px" },
  { key: "italic", title: "Italic", description: "Display projected text in italic style", keywords: ["italic", "style", "text", "font style", "oblique", "slanted"], aliases: ["font-italic", "text-italic"], tags: ["typography", "style"], type: "toggle", category: "text-formatting" },
  { key: "underline", title: "Underline", description: "Display projected text with underline decoration", keywords: ["underline", "text", "decoration", "style", "underscore"], aliases: ["text-underline", "font-underline"], tags: ["typography", "decoration"], type: "toggle", category: "text-formatting" },
  { key: "shadowEnabled", title: "Text Shadow", description: "Add a drop shadow behind projected text for readability", keywords: ["shadow", "text", "drop", "depth", "effect", "readability"], aliases: ["drop-shadow", "text-shadow"], tags: ["effect", "text"], type: "toggle", category: "text-formatting" },
  { key: "shadowBlur", title: "Shadow Blur", description: "Blur radius of the text shadow effect", keywords: ["shadow", "blur", "softness", "spread", "radius"], aliases: ["shadow-radius", "shadow-softness"], tags: ["effect", "shadow"], type: "slider", category: "text-formatting", min: 0, max: 20, step: 0.5, unit: "px" },
  { key: "shadowOpacity", title: "Shadow Opacity", description: "Opacity of the text shadow", keywords: ["shadow", "opacity", "transparency", "alpha", "fade"], aliases: ["shadow-alpha", "shadow-strength"], tags: ["effect", "shadow"], type: "slider", category: "text-formatting", min: 0, max: 100, step: 5, unit: "%" },
  { key: "outlineEnabled", title: "Text Outline", description: "Add an outline stroke around text characters", keywords: ["outline", "stroke", "border", "text", "edge", "contour"], aliases: ["stroke", "text-outline"], tags: ["effect", "text"], type: "toggle", category: "text-formatting" },
  { key: "outlineWidth", title: "Outline Width", description: "Thickness of the text outline stroke in pixels", keywords: ["outline", "width", "stroke", "thickness", "border", "size"], aliases: ["stroke-width", "outline-thickness"], tags: ["effect", "outline"], type: "slider", category: "text-formatting", min: 0, max: 10, step: 0.5, unit: "px" },
  { key: "outlineColor", title: "Outline Color", description: "Color of the text outline stroke", keywords: ["outline", "color", "stroke", "border", "edge"], aliases: ["stroke-color", "outline-stroke"], tags: ["effect", "color"], type: "color", category: "text-formatting" },
  { key: "strokeJoin", title: "Stroke Join", description: "Shape of the corners in the text outline", keywords: ["stroke", "join", "miter", "round", "bevel", "corner"], aliases: ["line-join", "corner-style"], tags: ["effect", "shape"], type: "select", category: "text-formatting", options: [{ value: "miter", label: "Miter" }, { value: "round", label: "Round" }, { value: "bevel", label: "Bevel" }] },
  { key: "glowEnabled", title: "Text Glow", description: "Add a soft glow effect behind text", keywords: ["glow", "neon", "text", "light", "bloom", "radiance"], aliases: ["neon-glow", "text-glow"], tags: ["effect", "text"], type: "toggle", category: "text-formatting" },
  { key: "glowColor", title: "Glow Color", description: "Color of the text glow effect", keywords: ["glow", "color", "neon", "light", "bloom", "radiant"], aliases: ["neon-color", "glow-tint"], tags: ["effect", "color"], type: "color", category: "text-formatting" },
  { key: "textOpacity", title: "Text Opacity", description: "Opacity level of projected text", keywords: ["text", "opacity", "transparency", "alpha", "fade"], aliases: ["text-alpha", "text-transparency"], tags: ["text", "opacity"], type: "slider", category: "text-formatting", min: 0, max: 100, step: 5, unit: "%" },
  { key: "referenceOpacity", title: "Reference Opacity", description: "Opacity level of Bible reference text", keywords: ["reference", "opacity", "verse", "citation", "bible", "fade"], aliases: ["verse-opacity", "reference-alpha"], tags: ["bible", "opacity"], type: "slider", category: "text-formatting", min: 0, max: 100, step: 5, unit: "%" },

  // ════════════════════ Themes ════════════════════
  { key: "defaultThemeId", title: "Default Theme", description: "Theme applied to new projects", keywords: ["theme", "template", "default", "preset", "style"], aliases: ["default-template", "start-theme"], tags: ["themes", "defaults"], type: "input", category: "themes", placeholder: "worship-royal-sapphire" },
  { key: "animatedThemesEnabled", title: "Animated Themes", description: "Enable animated background themes with motion effects", keywords: ["animated", "theme", "animation", "motion", "background", "dynamic"], aliases: ["enable-animations", "theme-motion"], tags: ["themes", "animation"], type: "toggle", category: "themes" },
  { key: "themeTransitionSpeed", title: "Theme Transition Speed", description: "Speed of theme switching animation", keywords: ["theme", "transition", "speed", "animation", "switch", "duration"], aliases: ["theme-switch-speed", "animation-speed"], tags: ["themes", "timing"], type: "slider", category: "themes", min: 100, max: 2000, step: 100, unit: "ms" },
  { key: "themeAutoApply", title: "Auto-Apply Theme", description: "Automatically apply theme styles when selected", keywords: ["theme", "auto", "apply", "instant", "preview"], aliases: ["auto-apply", "instant-apply"], tags: ["themes", "behavior"], type: "toggle", category: "themes" },
  { key: "backgroundOpacity", title: "Background Opacity", description: "Opacity of the theme background", keywords: ["background", "opacity", "transparency", "theme", "alpha"], aliases: ["bg-opacity", "theme-bg-alpha"], tags: ["themes", "opacity"], type: "slider", category: "themes", min: 0, max: 100, step: 5, unit: "%" },
  { key: "backgroundBlur", title: "Background Blur", description: "Blur amount applied to the theme background", keywords: ["background", "blur", "theme", "backdrop", "soften"], aliases: ["bg-blur", "background-softness"], tags: ["themes", "effects"], type: "slider", category: "themes", min: 0, max: 50, step: 1, unit: "px" },
  { key: "particlesEnabled", title: "Particles", description: "Floating particle effects in the background", keywords: ["particles", "floating", "dots", "ambient", "background", "effect"], aliases: ["particle-system", "float-particles"], tags: ["effects", "ambient"], type: "toggle", category: "themes" },
  { key: "lightRaysEnabled", title: "Light Rays", description: "God ray light effects in the background", keywords: ["light", "rays", "god rays", "sun", "volumetric", "shafts"], aliases: ["god-rays", "sun-rays"], tags: ["effects", "light"], type: "toggle", category: "themes" },
  { key: "starsEnabled", title: "Stars", description: "Twinkling star field in the background", keywords: ["stars", "night", "sky", "twinkle", "space", "cosmic"], aliases: ["starfield", "night-sky"], tags: ["effects", "sky"], type: "toggle", category: "themes" },
  { key: "fogEnabled", title: "Fog", description: "Atmospheric fog effect in the background", keywords: ["fog", "mist", "atmosphere", "haze", "cloud", "weather"], aliases: ["mist", "atmospheric-fog"], tags: ["effects", "atmosphere"], type: "toggle", category: "themes" },
  { key: "smokeEnabled", title: "Smoke", description: "Smoke particle effect in the background", keywords: ["smoke", "smoke effect", "particles", "ambient", "haze"], aliases: ["smoke-particles", "haze-effect"], tags: ["effects", "particles"], type: "toggle", category: "themes" },
  { key: "rainEnabled", title: "Rain", description: "Rainfall effect in the background", keywords: ["rain", "weather", "water", "precipitation", "storm", "drops"], aliases: ["rain-effect", "rainfall"], tags: ["effects", "weather"], type: "toggle", category: "themes" },
  { key: "snowEnabled", title: "Snow", description: "Snowfall effect in the background", keywords: ["snow", "winter", "weather", "snowflakes", "snowfall", "flakes"], aliases: ["snow-effect", "snowfall"], tags: ["effects", "weather"], type: "toggle", category: "themes" },
  { key: "bokehEnabled", title: "Bokeh", description: "Soft bokeh light effect in the background", keywords: ["bokeh", "blur", "lights", "circles", "photography", "soft"], aliases: ["bokeh-lights", "bokeh-effect"], tags: ["effects", "light"], type: "toggle", category: "themes" },
  { key: "auroraEnabled", title: "Aurora", description: "Northern lights aurora effect in the background", keywords: ["aurora", "northern lights", "borealis", "lights", "sky", "glow"], aliases: ["northern-lights", "aurora-borealis"], tags: ["effects", "sky"], type: "toggle", category: "themes" },
  { key: "meshGradientEnabled", title: "Mesh Gradient", description: "Smooth mesh gradient animation in the background", keywords: ["mesh", "gradient", "smooth", "blend", "color", "fluid"], aliases: ["fluid-gradient", "mesh-bg"], tags: ["effects", "gradient"], type: "toggle", category: "themes" },
  { key: "motionBackgroundEnabled", title: "Motion Background", description: "Animated motion background effects", keywords: ["motion", "background", "animated", "moving", "dynamic"], aliases: ["motion-bg", "animated-background"], tags: ["effects", "motion"], type: "toggle", category: "themes" },
  { key: "videoBackgroundEnabled", title: "Video Background", description: "Use a video file as the theme background", keywords: ["video", "background", "looping", "bg video", "motion"], aliases: ["bg-video", "video-bg"], tags: ["effects", "video"], type: "toggle", category: "themes" },

  // ═══════════════════════ Bible ═══════════════════════
  { key: "defaultTranslation", title: "Default Translation", description: "Primary Bible translation for display", keywords: ["bible", "translation", "version", "scripture", "text", "word"], aliases: ["bible-version", "scripture-translation"], tags: ["bible", "translation"], type: "select", category: "bible", options: [{ value: "en", label: "English" }, { value: "ta", label: "Tamil" }] },
  { key: "defaultVersion", title: "Default Version", description: "Default Bible version text identifier", keywords: ["bible", "version", "default", "kjv", "niv", "esv"], aliases: ["default-bible", "bible-version"], tags: ["bible", "version"], type: "input", category: "bible", placeholder: "KJV" },
  { key: "tamilVersion", title: "Tamil Version", description: "Tamil Bible version identifier", keywords: ["tamil", "bible", "version", "tamil bible", "tcv"], aliases: ["ta-version", "tamil-bible-version"], tags: ["bible", "tamil", "version"], type: "input", category: "bible", placeholder: "TCV" },
  { key: "englishVersion", title: "English Version", description: "English Bible version identifier", keywords: ["english", "bible", "version", "kjv", "niv", "esv"], aliases: ["en-version", "english-bible-version"], tags: ["bible", "english", "version"], type: "input", category: "bible", placeholder: "KJV" },
  { key: "tamilFirst", title: "Tamil First", description: "Show Tamil text as the primary reference", keywords: ["tamil", "primary", "language", "order", "priority", "first"], aliases: ["tamil-priority", "prefer-tamil"], tags: ["bible", "tamil", "display"], type: "toggle", category: "bible" },
  { key: "parallelMode", title: "Parallel Mode", description: "Show English and Tamil translations side by side", keywords: ["parallel", "dual", "side by side", "bilingual", "both", "languages"], aliases: ["dual-pane", "side-by-side"], tags: ["bible", "display", "layout"], type: "toggle", category: "bible" },
  { key: "bookAbbreviations", title: "Book Abbreviations", description: "Use abbreviated book names in bible references", keywords: ["book", "abbreviation", "short", "name", "reference", "shorthand"], aliases: ["short-names", "abbreviated-books"], tags: ["bible", "display"], type: "toggle", category: "bible" },
  { key: "bookNameStyle", title: "Book Name Style", description: "Style of book names displayed in references", keywords: ["book", "name", "style", "full", "abbreviated", "short"], aliases: ["book-style", "name-format"], tags: ["bible", "display", "format"], type: "select", category: "bible", options: [{ value: "full", label: "Full" }, { value: "abbreviated", label: "Abbreviated" }, { value: "short", label: "Short" }] },
  { key: "verseNumbering", title: "Verse Numbering", description: "Show verse numbers in scripture display", keywords: ["verse", "number", "reference", "scripture", "chapter"], aliases: ["show-verses", "verse-numbers"], tags: ["bible", "display"], type: "toggle", category: "bible" },
  { key: "showReference", title: "Show Reference", description: "Display the scripture reference on screen", keywords: ["reference", "verse", "citation", "show", "display"], aliases: ["show-verse-ref", "display-reference"], tags: ["bible", "display"], type: "toggle", category: "bible" },
  { key: "referencePosition", title: "Reference Position", description: "Position of the scripture reference on screen", keywords: ["reference", "position", "top", "bottom", "overlay", "verse"], aliases: ["verse-position", "ref-placement"], tags: ["bible", "layout"], type: "select", category: "bible", options: [{ value: "bottom", label: "Bottom" }, { value: "top", label: "Top" }, { value: "overlay", label: "Overlay" }] },
  { key: "referenceSize", title: "Reference Size", description: "Font size of the bible reference text in pixels", keywords: ["reference", "size", "font", "verse", "small", "text"], aliases: ["ref-font-size", "verse-size"], tags: ["bible", "typography"], type: "slider", category: "bible", min: 8, max: 48, unit: "px" },
  { key: "tanglishSearch", title: "Tanglish Bible Search", description: "Search Tamil Bible using Roman characters", keywords: ["tamil", "tanglish", "search", "roman", "transliteration", "english"], aliases: ["roman-search", "tamil-roman"], tags: ["bible", "search", "tamil"], type: "toggle", category: "bible" },
  { key: "phoneticSearch", title: "Phonetic Bible Search", description: "Match phonetically similar words during bible search", keywords: ["phonetic", "sound", "similar", "fuzzy", "search", "approximate"], aliases: ["fuzzy-search", "sound-search"], tags: ["bible", "search"], type: "toggle", category: "bible" },
  { key: "verseSplit", title: "Verse Split Mode", description: "How verses are split in the display", keywords: ["verse", "split", "single", "range", "chapter", "display"], aliases: ["split-mode", "verse-division"], tags: ["bible", "display", "layout"], type: "select", category: "bible", options: [{ value: "single", label: "Single Verse" }, { value: "range", label: "Verse Range" }, { value: "chapter", label: "Full Chapter" }] },
  { key: "autoAdvance", title: "Auto Advance Verses", description: "Automatically advance to the next verse", keywords: ["auto", "advance", "verse", "next", "automatic", "bible"], aliases: ["auto-verse", "verse-advance"], tags: ["bible", "playback"], type: "toggle", category: "bible" },
  { key: "verseAnimation", title: "Verse Animation", description: "Animate verse transitions in the display", keywords: ["verse", "animation", "transition", "effect", "bible", "motion"], aliases: ["verse-transition", "bible-animation"], tags: ["bible", "animation"], type: "toggle", category: "bible" },

  // ═══════════════════════ Songs ═══════════════════════
  { key: "songsDefaultLanguage", title: "Song Language", description: "Default language for the song library", keywords: ["song", "language", "tamil", "english", "lyrics", "worship"], aliases: ["lyric-language", "song-lang"], tags: ["songs", "language"], type: "select", category: "songs", options: [{ value: "ta", label: "Tamil" }, { value: "en", label: "English" }] },
  { key: "defaultSearchMode", title: "Search Mode", description: "Default search mode for finding songs", keywords: ["search", "mode", "title", "lyrics", "both", "song"], aliases: ["song-search-mode", "search-type"], tags: ["songs", "search"], type: "select", category: "songs", options: [{ value: "title", label: "Title" }, { value: "lyrics", label: "Lyrics" }, { value: "both", label: "Title & Lyrics" }] },
  { key: "tanglishSearchEnabled", title: "Tanglish Song Search", description: "Search songs using Romanized Tamil text", keywords: ["tamil", "tanglish", "search", "roman", "song", "lyrics"], aliases: ["song-tanglish", "roman-lyric-search"], tags: ["songs", "search", "tamil"], type: "toggle", category: "songs" },
  { key: "fuzzySearch", title: "Fuzzy Search", description: "Find songs with approximate matching", keywords: ["fuzzy", "search", "approximate", "close", "similar", "typo"], aliases: ["fuzzy-matching", "approximate-search"], tags: ["songs", "search"], type: "toggle", category: "songs" },
  { key: "soundSimilarSearch", title: "Sound Similar Search", description: "Match songs that sound similar phonetically", keywords: ["sound", "similar", "phonetic", "homophone", "sounds like"], aliases: ["sounds-like", "phonetic-song"], tags: ["songs", "search"], type: "toggle", category: "songs" },
  { key: "autoCapitalization", title: "Auto Capitalization", description: "Automatically capitalize song titles and lyrics", keywords: ["capitalize", "auto", "title", "lyrics", "format", "case"], aliases: ["auto-cap", "capitalize-text"], tags: ["songs", "formatting"], type: "toggle", category: "songs" },
  { key: "defaultSorting", title: "Song Sorting", description: "Default sort order for song listings", keywords: ["sort", "order", "song", "list", "arrange", "alphabetical"], aliases: ["sort-order", "list-order"], tags: ["songs", "sorting"], type: "select", category: "songs", options: [{ value: "title", label: "Title" }, { value: "recent", label: "Recently Used" }, { value: "created", label: "Date Added" }, { value: "artist", label: "Artist" }] },
  { key: "autoLoadLyrics", title: "Auto-Load Lyrics", description: "Preload lyrics when a song is selected", keywords: ["lyrics", "auto", "load", "prefetch", "song", "cache"], aliases: ["preload-lyrics", "cache-lyrics"], tags: ["songs", "performance"], type: "toggle", category: "songs" },
  { key: "songCacheSize", title: "Song Cache Size", description: "Maximum number of songs to cache in memory", keywords: ["cache", "song", "size", "memory", "max", "limit"], aliases: ["cache-limit", "max-songs-cached"], tags: ["songs", "performance", "cache"], type: "number", category: "songs", min: 50, max: 5000, unit: "songs" },

  // ═══════════════════════ Media ═══════════════════════
  { key: "imageDurationMs", title: "Image Duration", description: "Display duration for images in the playlist", keywords: ["image", "duration", "time", "photo", "slide", "seconds"], aliases: ["image-time", "photo-duration"], tags: ["media", "timing"], type: "number", category: "media", min: 1, max: 3600, unit: "s" },
  { key: "videoAutoplay", title: "Autoplay Videos", description: "Automatically start video playback when selected", keywords: ["video", "autoplay", "play", "start", "media"], aliases: ["auto-start-video", "video-auto"], tags: ["media", "playback"], type: "toggle", category: "media" },
  { key: "mediaLoop", title: "Loop Media", description: "Loop media playback continuously", keywords: ["loop", "repeat", "media", "video", "cycle", "continuous"], aliases: ["repeat-media", "loop-playback"], tags: ["media", "playback"], type: "toggle", category: "media" },
  { key: "hardwareAcceleration", title: "Hardware Acceleration", description: "Use GPU acceleration for media rendering", keywords: ["gpu", "hardware", "acceleration", "render", "performance", "graphics"], aliases: ["gpu-accel", "hardware-render"], tags: ["media", "performance"], type: "toggle", category: "media" },
  { key: "thumbnailQuality", title: "Thumbnail Quality", description: "Quality level for generated thumbnails", keywords: ["thumbnail", "quality", "preview", "image", "resolution", "thumb"], aliases: ["preview-quality", "thumb-quality"], tags: ["media", "quality"], type: "select", category: "media", options: [{ value: "low", label: "Low" }, { value: "medium", label: "Medium" }, { value: "high", label: "High" }] },
  { key: "gifPlayback", title: "GIF Playback Mode", description: "How animated GIFs are played back", keywords: ["gif", "playback", "animation", "loop", "once", "pause"], aliases: ["gif-mode", "animation-playback"], tags: ["media", "playback"], type: "select", category: "media", options: [{ value: "animate", label: "Animate" }, { value: "once", label: "Play Once" }, { value: "pause", label: "Pause" }] },
  { key: "imageScaling", title: "Image Scaling", description: "How images are scaled to fit the screen", keywords: ["image", "scaling", "fit", "fill", "stretch", "tile"], aliases: ["img-fit", "image-fit"], tags: ["media", "display"], type: "select", category: "media", options: [{ value: "fill", label: "Fill" }, { value: "fit", label: "Fit" }, { value: "stretch", label: "Stretch" }, { value: "tile", label: "Tile" }] },
  { key: "videoScaling", title: "Video Scaling", description: "How videos are scaled to fit the screen", keywords: ["video", "scaling", "fit", "fill", "stretch", "display"], aliases: ["video-fit", "vid-scaling"], tags: ["media", "display"], type: "select", category: "media", options: [{ value: "fill", label: "Fill" }, { value: "fit", label: "Fit" }, { value: "stretch", label: "Stretch" }] },

  // ═══════════════════════ Search ═══════════════════════
  { key: "instantSearch", title: "Instant Search", description: "Show results as you type without waiting", keywords: ["instant", "search", "type", "live", "real-time", "results"], aliases: ["live-search", "real-time-search"], tags: ["search", "behavior"], type: "toggle", category: "search" },
  { key: "searchHistory", title: "Search History", description: "Remember recent search queries", keywords: ["history", "search", "recent", "remember", "queries", "log"], aliases: ["remember-searches", "search-log"], tags: ["search", "history"], type: "toggle", category: "search" },
  { key: "maxResults", title: "Maximum Results", description: "Maximum number of search results to display", keywords: ["max", "results", "limit", "search", "count", "maximum"], aliases: ["result-limit", "max-search-results"], tags: ["search", "limits"], type: "number", category: "search", min: 10, max: 500 },
  { key: "cacheSize", title: "Search Cache Size", description: "Number of search results to cache for faster repeat searches", keywords: ["cache", "search", "size", "results", "memory", "speed"], aliases: ["search-cache", "result-cache"], tags: ["search", "performance", "cache"], type: "number", category: "search", min: 50, max: 2000 },
  { key: "searchDelay", title: "Search Delay", description: "Delay in milliseconds before search triggers after typing", keywords: ["delay", "search", "debounce", "wait", "type", "throttle"], aliases: ["debounce-ms", "search-throttle"], tags: ["search", "performance"], type: "slider", category: "search", min: 0, max: 1000, step: 50, unit: "ms" },
  { key: "indexAutomatically", title: "Index Automatically", description: "Automatically index new content for search", keywords: ["index", "auto", "search", "automatic", "content"], aliases: ["auto-index", "automatic-indexing"], tags: ["search", "indexing"], type: "toggle", category: "search" },
  { key: "backgroundIndexing", title: "Background Indexing", description: "Index search data in the background", keywords: ["background", "indexing", "search", "performance", "thread"], aliases: ["bg-indexing", "offline-index"], tags: ["search", "performance"], type: "toggle", category: "search" },

  // ═══════════════════════ Performance ═══════════════════════
  { key: "gpuRendering", title: "GPU Rendering", description: "Use GPU for rendering when available", keywords: ["gpu", "render", "graphics", "performance", "hardware"], aliases: ["gpu-acceleration", "render-engine"], tags: ["performance", "rendering"], type: "toggle", category: "performance" },
  { key: "memoryCache", title: "Memory Cache", description: "Cache frequently accessed data in memory", keywords: ["memory", "cache", "ram", "speed", "performance"], aliases: ["ram-cache", "in-memory-cache"], tags: ["performance", "cache"], type: "toggle", category: "performance" },
  { key: "themeCache", title: "Theme Cache", description: "Cache theme assets for faster switching", keywords: ["theme", "cache", "performance", "switch", "speed"], aliases: ["cache-themes", "theme-caching"], tags: ["performance", "cache", "themes"], type: "toggle", category: "performance" },
  { key: "imageCache", title: "Image Cache", description: "Cache image thumbnails and previews", keywords: ["image", "cache", "thumbnails", "preview", "performance"], aliases: ["cache-images", "image-caching"], tags: ["performance", "cache", "media"], type: "toggle", category: "performance" },
  { key: "videoCache", title: "Video Cache", description: "Cache video metadata and thumbnails", keywords: ["video", "cache", "metadata", "thumbnails", "performance"], aliases: ["cache-videos", "video-caching"], tags: ["performance", "cache", "media"], type: "toggle", category: "performance" },
  { key: "songCache", title: "Song Cache", description: "Cache song data for faster access", keywords: ["song", "cache", "lyrics", "performance", "speed"], aliases: ["cache-songs", "lyric-cache"], tags: ["performance", "cache", "songs"], type: "toggle", category: "performance" },
  { key: "bibleCache", title: "Bible Cache", description: "Cache bible data for faster verse access", keywords: ["bible", "cache", "scripture", "verses", "performance"], aliases: ["cache-bible", "scripture-cache"], tags: ["performance", "cache", "bible"], type: "toggle", category: "performance" },
  { key: "preloadDatasets", title: "Preload Datasets", description: "Load Bible and Songs data in the background on startup", keywords: ["preload", "data", "background", "cache", "load", "bible", "songs"], aliases: ["background-load", "data-prefetch"], tags: ["performance", "startup"], type: "toggle", category: "performance" },
  { key: "preloadSongs", title: "Preload Songs", description: "Preload song library on application startup", keywords: ["preload", "songs", "load", "startup", "background"], aliases: ["songs-preload", "prefetch-songs"], tags: ["performance", "startup", "songs"], type: "toggle", category: "performance" },
  { key: "preloadBible", title: "Preload Bible", description: "Preload Bible data on application startup", keywords: ["preload", "bible", "load", "startup", "background"], aliases: ["bible-preload", "prefetch-bible"], tags: ["performance", "startup", "bible"], type: "toggle", category: "performance" },
  { key: "lazyLoading", title: "Lazy Loading", description: "Load media thumbnails on demand instead of all at once", keywords: ["lazy", "load", "on-demand", "thumbnail", "deferred"], aliases: ["defer-load", "on-demand"], tags: ["performance", "loading"], type: "toggle", category: "performance" },
  { key: "databaseOptimization", title: "Database Optimization", description: "Periodically optimize the database for better performance", keywords: ["database", "optimize", "performance", "compact", "vacuum"], aliases: ["db-optimization", "compact-database"], tags: ["performance", "database"], type: "toggle", category: "performance" },

  // ═══════════════════════ Audio ═══════════════════════
  { key: "outputDevice", title: "Output Device", description: "Primary audio output device for media playback", keywords: ["audio", "output", "device", "speaker", "sound", "playback"], aliases: ["audio-device", "sound-output"], tags: ["audio", "hardware"], type: "select", category: "audio", options: [{ value: "default", label: "System Default" }] },
  { key: "masterVolume", title: "Master Volume", description: "Global audio output volume level", keywords: ["volume", "master", "audio", "sound", "level", "global"], aliases: ["global-volume", "main-volume"], tags: ["audio", "volume"], type: "slider", category: "audio", min: 0, max: 100, step: 5, unit: "%" },
  { key: "audioVolume", title: "Media Volume", description: "Default volume level for media playback", keywords: ["volume", "media", "audio", "sound", "level"], aliases: ["media-volume", "playback-volume"], tags: ["audio", "volume"], type: "slider", category: "audio", min: 0, max: 100, step: 5, unit: "%" },
  { key: "previewVolume", title: "Preview Volume", description: "Volume level for audio previews", keywords: ["preview", "volume", "audio", "sound", "level", "sample"], aliases: ["preview-level", "sample-volume"], tags: ["audio", "preview"], type: "slider", category: "audio", min: 0, max: 100, step: 5, unit: "%" },
  { key: "fadeInMs", title: "Audio Fade In", description: "Duration of audio fade-in effect at playback start", keywords: ["fade", "in", "audio", "transition", "ramp", "smooth"], aliases: ["fade-in", "ramp-in"], tags: ["audio", "transitions"], type: "number", category: "audio", min: 0, max: 5000, step: 100, unit: "ms" },
  { key: "fadeOutMs", title: "Audio Fade Out", description: "Duration of audio fade-out effect at playback end", keywords: ["fade", "out", "audio", "transition", "ramp", "smooth"], aliases: ["fade-out", "ramp-out"], tags: ["audio", "transitions"], type: "number", category: "audio", min: 0, max: 5000, step: 100, unit: "ms" },
  { key: "audioDelay", title: "Audio Delay", description: "Audio delay in milliseconds for synchronization", keywords: ["delay", "audio", "sync", "latency", "offset"], aliases: ["audio-latency", "sync-delay"], tags: ["audio", "sync"], type: "number", category: "audio", min: 0, max: 2000, step: 10, unit: "ms" },
  { key: "defaultOutput", title: "Default Output", description: "Default audio output device identifier", keywords: ["default", "output", "audio", "device", "speaker"], aliases: ["default-device", "primary-output"], tags: ["audio", "hardware"], type: "select", category: "audio", options: [{ value: "default", label: "System Default" }] },
  { key: "microphone", title: "Microphone", description: "Microphone input device for live audio", keywords: ["microphone", "mic", "audio", "input", "voice", "speak"], aliases: ["mic-input", "audio-input"], tags: ["audio", "input"], type: "select", category: "audio", options: [{ value: "default", label: "System Default" }] },
  { key: "muteOnStartup", title: "Mute on Startup", description: "Start the application with audio muted", keywords: ["mute", "silent", "startup", "audio", "sound", "quiet"], aliases: ["start-muted", "silent-start"], tags: ["audio", "startup"], type: "toggle", category: "audio" },

  // ═══════════════════════ Video ═══════════════════════
  { key: "hardwareDecoding", title: "Hardware Decoding", description: "Use hardware-accelerated video decoding", keywords: ["video", "decoding", "hardware", "gpu", "codec", "h264", "hevc"], aliases: ["gpu-decode", "hardware-decode"], tags: ["video", "performance"], type: "toggle", category: "video" },
  { key: "frameRate", title: "Frame Rate", description: "Target frame rate for video playback", keywords: ["fps", "frame", "rate", "video", "smooth", "refresh"], aliases: ["target-fps", "playback-fps"], tags: ["video", "quality"], type: "select", category: "video", options: [{ value: "24", label: "24 FPS" }, { value: "30", label: "30 FPS" }, { value: "60", label: "60 FPS" }] },
  { key: "defaultResolution", title: "Default Resolution", description: "Default video resolution for new imports", keywords: ["resolution", "video", "default", "import", "quality"], aliases: ["video-resolution", "import-resolution"], tags: ["video", "quality"], type: "select", category: "video", options: [{ value: "1920x1080", label: "1920 × 1080 (Full HD)" }, { value: "3840x2160", label: "3840 × 2160 (4K)" }, { value: "1280x720", label: "1280 × 720 (HD)" }] },
  { key: "defaultCodec", title: "Default Codec", description: "Preferred video codec for encoding", keywords: ["codec", "video", "h264", "h265", "hevc", "vp9", "av1"], aliases: ["video-codec", "encoding-codec"], tags: ["video", "encoding"], type: "select", category: "video", options: [{ value: "h264", label: "H.264" }, { value: "h265", label: "H.265 / HEVC" }, { value: "vp9", label: "VP9" }, { value: "av1", label: "AV1" }] },
  { key: "imageQuality", title: "Image Quality", description: "Default quality level for image processing", keywords: ["image", "quality", "compression", "encoding", "jpeg", "png"], aliases: ["img-quality", "image-compression"], tags: ["media", "quality"], type: "slider", category: "video", min: 10, max: 100, step: 5, unit: "%" },
  { key: "videoQuality", title: "Video Quality", description: "Default quality level for video encoding", keywords: ["video", "quality", "encoding", "compression", "bitrate"], aliases: ["vid-quality", "video-compression"], tags: ["video", "quality"], type: "slider", category: "video", min: 10, max: 100, step: 5, unit: "%" },
  { key: "scalingAlgorithm", title: "Scaling Algorithm", description: "Algorithm used for upscaling or downscaling video", keywords: ["scaling", "algorithm", "nearest", "bilinear", "bicubic", "upscale"], aliases: ["resize-method", "upscale-algo"], tags: ["video", "quality"], type: "select", category: "video", options: [{ value: "nearest", label: "Nearest Neighbor" }, { value: "bilinear", label: "Bilinear" }, { value: "bicubic", label: "Bicubic" }] },

  // ═══════════════════════ Remote Control ═══════════════════════
  { key: "remoteEnabled", title: "Enable Remote Control", description: "Allow remote devices to control the presentation", keywords: ["remote", "control", "enable", "network", "device"], aliases: ["enable-remote", "remote-access"], tags: ["remote", "network"], type: "toggle", category: "remote-control" },
  { key: "webRemoteEnabled", title: "Web Remote", description: "Enable web browser-based remote control", keywords: ["web", "remote", "browser", "http", "control"], aliases: ["web-access", "browser-remote"], tags: ["remote", "web"], type: "toggle", category: "remote-control" },
  { key: "mobileRemoteEnabled", title: "Mobile Remote", description: "Enable mobile device remote control", keywords: ["mobile", "remote", "phone", "tablet", "app"], aliases: ["phone-remote", "mobile-access"], tags: ["remote", "mobile"], type: "toggle", category: "remote-control" },
  { key: "qrCodeEnabled", title: "QR Code", description: "Show QR code for quick remote connection", keywords: ["qr", "code", "scan", "connect", "remote"], aliases: ["qr-connect", "scan-to-connect"], tags: ["remote", "connectivity"], type: "toggle", category: "remote-control" },
  { key: "pinCode", title: "PIN Code", description: "PIN code required to connect remotely", keywords: ["pin", "code", "security", "remote", "password", "auth"], aliases: ["remote-pin", "access-code"], tags: ["remote", "security"], type: "input", category: "remote-control", placeholder: "Not set" },
  { key: "remoteLatency", title: "Latency", description: "Network latency compensation in milliseconds", keywords: ["latency", "delay", "network", "sync", "remote"], aliases: ["network-delay", "sync-offset"], tags: ["remote", "network"], type: "slider", category: "remote-control", min: 0, max: 500, step: 10, unit: "ms" },
  { key: "remoteReconnect", title: "Auto Reconnect", description: "Automatically reconnect remote control on connection loss", keywords: ["reconnect", "auto", "remote", "connection", "retry"], aliases: ["auto-reconnect", "retry-connection"], tags: ["remote", "network"], type: "toggle", category: "remote-control" },

  // ═══════════════════════ Backup ═══════════════════════
  { key: "automaticBackup", title: "Automatic Backup", description: "Automatically create periodic backups", keywords: ["backup", "auto", "automatic", "scheduled", "periodic"], aliases: ["auto-backup", "scheduled-backup"], tags: ["backup", "automation"], type: "toggle", category: "backup" },
  { key: "backupInterval", title: "Backup Interval", description: "Hours between automatic backups", keywords: ["backup", "interval", "hours", "frequency", "period"], aliases: ["backup-frequency", "backup-hours"], tags: ["backup", "scheduling"], type: "number", category: "backup", min: 1, max: 168, unit: "h" },
  { key: "cloudBackup", title: "Cloud Backup", description: "Upload backups to cloud storage", keywords: ["cloud", "backup", "sync", "online", "storage", "remote"], aliases: ["cloud-sync", "online-backup"], tags: ["backup", "cloud"], type: "toggle", category: "backup" },
  { key: "backupLocation", title: "Backup Location", description: "Directory path for storing backup files", keywords: ["backup", "location", "path", "directory", "folder", "storage"], aliases: ["backup-path", "backup-folder"], tags: ["backup", "storage"], type: "input", category: "backup", placeholder: "Default" },

  // ═══════════════════════ Security ═══════════════════════
  { key: "lockSettings", title: "Lock Settings", description: "Require confirmation before changing settings", keywords: ["lock", "protect", "confirm", "settings", "security"], aliases: ["protect-settings", "settings-lock"], tags: ["security", "settings"], type: "toggle", category: "security" },
  { key: "requirePassword", title: "Require Password", description: "Require a password to access settings", keywords: ["password", "protect", "secure", "auth", "access", "lock"], aliases: ["password-protect", "auth-required"], tags: ["security", "authentication"], type: "toggle", category: "security" },
  { key: "settingsPassword", title: "Settings Password", description: "Password required to access settings", keywords: ["password", "settings", "protect", "secure", "auth"], aliases: ["settings-pin", "admin-password"], tags: ["security", "password"], type: "input", category: "security", placeholder: "••••••••" },
  { key: "readOnlyMode", title: "Read-Only Mode", description: "Prevent accidental changes to content and settings", keywords: ["read", "only", "lock", "protect", "prevent", "changes"], aliases: ["locked-mode", "prevent-changes"], tags: ["security", "protection"], type: "toggle", category: "security" },
  { key: "encryptDatabase", title: "Encrypt Database", description: "Encrypt the local database for enhanced security", keywords: ["encrypt", "database", "security", "crypto", "protect"], aliases: ["db-encryption", "encrypt-local"], tags: ["security", "encryption"], type: "toggle", category: "security" },
  { key: "backupEncryption", title: "Backup Encryption", description: "Encrypt backup files", keywords: ["backup", "encrypt", "security", "protect", "crypto"], aliases: ["encrypt-backup", "backup-protect"], tags: ["security", "encryption", "backup"], type: "toggle", category: "security" },

  // ═══════════════════════ Advanced ═══════════════════════
  { key: "developerMode", title: "Developer Mode", description: "Enable developer tools and debug information", keywords: ["developer", "debug", "tools", "console", "dev", "inspect"], aliases: ["dev-mode", "debug-mode"], tags: ["advanced", "development"], type: "toggle", category: "advanced" },
  { key: "logLevel", title: "Log Level", description: "Verbosity level for application logging", keywords: ["log", "logging", "debug", "verbose", "error", "warn", "info"], aliases: ["logging-level", "verbosity"], tags: ["advanced", "debugging"], type: "select", category: "advanced", options: [{ value: "error", label: "Errors Only" }, { value: "warn", label: "Warnings" }, { value: "info", label: "Information" }, { value: "debug", label: "Debug" }] },
  { key: "experimentalFeatures", title: "Experimental Features", description: "Enable experimental and in-development features", keywords: ["experimental", "beta", "features", "preview", "unstable"], aliases: ["beta-features", "preview-mode"], tags: ["advanced", "features"], type: "toggle", category: "advanced" },
  { key: "factoryResetToken", title: "Factory Reset Token", description: "Token required for factory reset operations", keywords: ["reset", "factory", "token", "wipe", "restore"], aliases: ["reset-token", "wipe-token"], tags: ["advanced", "maintenance"], type: "input", category: "advanced", placeholder: "Not set" },
];

export const SETTINGS: SettingDef[] = ALL;
export const CATEGORIES: string[] = [...new Set(ALL.map((s) => s.category))];

export const CATEGORY_META: Record<string, { title: string; icon: LucideIcon }> = {
  general: { title: "General", icon: Settings },
  appearance: { title: "Appearance", icon: Palette },
  projection: { title: "Projection", icon: MonitorPlay },
  "text-formatting": { title: "Text Formatting", icon: Type },
  themes: { title: "Themes", icon: Sparkles },
  bible: { title: "Bible", icon: BookOpen },
  songs: { title: "Songs", icon: Music },
  media: { title: "Media", icon: Image },
  search: { title: "Search", icon: Search },
  performance: { title: "Performance", icon: Zap },
  audio: { title: "Audio", icon: Volume2 },
  video: { title: "Video", icon: Video },
  "remote-control": { title: "Remote Control", icon: Wifi },
  backup: { title: "Backup & Restore", icon: Download },
  security: { title: "Security", icon: Shield },
  advanced: { title: "Advanced", icon: Sliders },
};
