import type { AppSettings } from "@/db/schema";
import {
  Settings,
  MonitorPlay,
  Type,
  Sparkles,
  ListVideo,
  Download,
  Keyboard,
  Info,
  type LucideIcon,
} from "lucide-react";

export interface SettingDef {
  key: keyof AppSettings;
  title: string;
  description: string;
  keywords: string[];
  type: "toggle" | "slider" | "select" | "input" | "color" | "number";
  category: string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  placeholder?: string;
}

const ALL: SettingDef[] = [
  // ════════════════ General ════════════════
  {
    key: "theme",
    title: "Theme",
    description: "Switch between light, dark, or system theme",
    keywords: ["dark mode", "light mode", "system", "appearance", "night", "day", "interface"],
    type: "select",
    category: "general",
    options: [
      { value: "light", label: "Light" },
      { value: "dark", label: "Dark" },
      { value: "system", label: "System" },
    ],
  },
  {
    key: "language",
    title: "Language",
    description: "UI display language for the application",
    keywords: ["locale", "i18n", "region", "translation"],
    type: "select",
    category: "general",
    options: [{ value: "en", label: "English" }],
  },
  {
    key: "defaultStartupPage",
    title: "Startup Page",
    description: "Page shown when the application launches",
    keywords: ["start", "home", "landing", "default", "launch", "welcome"],
    type: "select",
    category: "general",
    options: [
      { value: "library", label: "Library" },
      { value: "project", label: "Project" },
      { value: "playlists", label: "Playlists" },
      { value: "settings", label: "Settings" },
    ],
  },
  {
    key: "startupBehavior",
    title: "Restore Last Session",
    description: "Reopen the previous workspace on launch",
    keywords: ["restore", "session", "launch", "startup", "remember", "previous"],
    type: "toggle",
    category: "general",
  },
  {
    key: "autoSave",
    title: "Auto Save",
    description: "Automatically save changes as you work",
    keywords: ["save", "auto", "persist", "automatic", "backup"],
    type: "toggle",
    category: "general",
  },

  // ════════════════ Projection ════════════════
  {
    key: "defaultDisplay",
    title: "Default Display",
    description: "Name or identifier of the output display",
    keywords: ["display", "monitor", "screen", "output", "projector"],
    type: "input",
    category: "projection",
    placeholder: "default",
  },
  {
    key: "projectorResolution",
    title: "Resolution",
    description: "Output resolution for the projector window",
    keywords: ["resolution", "display", "output", "screen", "monitor", "4k", "1080p", "hd"],
    type: "select",
    category: "projection",
    options: [
      { value: "1920x1080", label: "1920 × 1080 (Full HD)" },
      { value: "3840x2160", label: "3840 × 2160 (4K)" },
      { value: "1280x720", label: "1280 × 720 (HD)" },
      { value: "1024x768", label: "1024 × 768 (XGA)" },
    ],
  },
  {
    key: "aspectRatio",
    title: "Aspect Ratio",
    description: "Display aspect ratio for projection output",
    keywords: ["aspect", "ratio", "16:9", "4:3", "widescreen", "screen"],
    type: "select",
    category: "projection",
    options: [
      { value: "16:9", label: "16:9 (Widescreen)" },
      { value: "4:3", label: "4:3 (Standard)" },
      { value: "16:10", label: "16:10 (Wide)" },
      { value: "21:9", label: "21:9 (Ultrawide)" },
    ],
  },
  {
    key: "defaultBackground",
    title: "Default Background",
    description: "Background color shown when no content is projected",
    keywords: ["background", "color", "default", "empty", "idle", "black", "bg"],
    type: "color",
    category: "projection",
  },
  {
    key: "safeMargins",
    title: "Safe Area",
    description: "Safe area boundary as percentage of screen",
    keywords: ["safe", "margin", "boundary", "padding", "overscan", "border", "area"],
    type: "slider",
    category: "projection",
    min: 0,
    max: 20,
    unit: "%",
  },
  {
    key: "blackScreen",
    title: "Black Screen",
    description: "Press B key to toggle black screen between projected items",
    keywords: ["black", "screen", "blank", "between", "gap", "interval", "shortcut"],
    type: "toggle",
    category: "projection",
  },
  {
    key: "logoScreen",
    title: "Logo Screen",
    description: "Show logo when no content is projected",
    keywords: ["logo", "brand", "idle", "empty", "placeholder", "splash"],
    type: "toggle",
    category: "projection",
  },
  {
    key: "countdownSeconds",
    title: "Countdown Duration",
    description: "Default timer duration in seconds",
    keywords: ["countdown", "timer", "seconds", "count", "clock", "duration"],
    type: "number",
    category: "projection",
    min: 3,
    max: 300,
    unit: "s",
  },

  // ════════════════ Playlist ════════════════
  {
    key: "autoTransition",
    title: "Auto Advance",
    description: "Automatically advance to the next item in a playlist",
    keywords: ["auto", "transition", "advance", "next", "automatic", "play"],
    type: "toggle",
    category: "playlist",
  },
  {
    key: "defaultImageDurationMs",
    title: "Slide Duration",
    description: "Default display duration for images in milliseconds",
    keywords: ["image", "duration", "time", "photo", "slide", "seconds", "milliseconds"],
    type: "number",
    category: "playlist",
    min: 1000,
    max: 60000,
    step: 500,
    unit: "ms",
  },
  {
    key: "defaultTransition",
    title: "Transition Type",
    description: "Default transition effect between playlist items",
    keywords: ["transition", "effect", "animation", "crossfade", "fade", "zoom", "dissolve"],
    type: "select",
    category: "playlist",
    options: [
      { value: "fade", label: "Fade" },
      { value: "crossfade", label: "Crossfade" },
      { value: "zoom", label: "Zoom" },
      { value: "dissolve", label: "Dissolve" },
      { value: "none", label: "None" },
    ],
  },
  {
    key: "transitionDuration",
    title: "Transition Duration",
    description: "Duration of transitions between playlist items in milliseconds",
    keywords: ["transition", "duration", "speed", "animation", "time", "crossfade"],
    type: "slider",
    category: "playlist",
    min: 100,
    max: 3000,
    step: 100,
    unit: "ms",
  },
  {
    key: "mediaLoop",
    title: "Loop Playlist",
    description: "Loop playlist playback continuously",
    keywords: ["loop", "repeat", "playlist", "cycle", "continuous"],
    type: "toggle",
    category: "playlist",
  },

  // ════════════════ Typography ════════════════
  {
    key: "tamilFont",
    title: "Tamil Font",
    description: "Font family for Tamil scripture text",
    keywords: ["tamil", "font", "tamil font", "tamil text", "language", "typeface"],
    type: "input",
    category: "typography",
    placeholder: "Noto Sans Tamil",
  },
  {
    key: "englishFont",
    title: "English Font",
    description: "Font family for English scripture text",
    keywords: ["english", "font", "english font", "latin", "text", "typeface"],
    type: "input",
    category: "typography",
    placeholder: "Inter",
  },
  {
    key: "referenceFont",
    title: "Reference Font",
    description: "Font family for Bible reference and verse numbers",
    keywords: ["reference", "font", "bible", "verse", "citation", "typeface"],
    type: "input",
    category: "typography",
    placeholder: "Inter",
  },
  {
    key: "fontSize",
    title: "Font Size",
    description: "Size of projected text in pixels",
    keywords: ["font", "size", "text", "scale", "large", "small"],
    type: "slider",
    category: "typography",
    min: 12,
    max: 200,
    unit: "px",
  },
  {
    key: "fontWeight",
    title: "Font Weight",
    description: "Thickness of text characters",
    keywords: ["font", "weight", "bold", "thickness", "light", "medium", "heavy"],
    type: "slider",
    category: "typography",
    min: 300,
    max: 900,
    step: 100,
  },
  {
    key: "lineSpacing",
    title: "Line Height",
    description: "Vertical space between lines of text",
    keywords: ["line", "spacing", "height", "leading", "vertical", "gap"],
    type: "slider",
    category: "typography",
    min: 1,
    max: 3,
    step: 0.1,
  },
  {
    key: "letterSpacing",
    title: "Letter Spacing",
    description: "Space between characters in pixels",
    keywords: ["letter", "spacing", "tracking", "kerning", "character", "width"],
    type: "slider",
    category: "typography",
    min: -2,
    max: 8,
    step: 0.5,
    unit: "px",
  },
  {
    key: "textWidth",
    title: "Text Width",
    description: "Maximum width of text as percentage of screen",
    keywords: ["width", "text", "content", "container", "area", "wide"],
    type: "slider",
    category: "typography",
    min: 30,
    max: 100,
    step: 5,
    unit: "%",
  },
  {
    key: "textAlign",
    title: "Horizontal Alignment",
    description: "Horizontal alignment of projected text",
    keywords: ["align", "left", "center", "right", "text", "horizontal"],
    type: "select",
    category: "typography",
    options: [
      { value: "left", label: "Left" },
      { value: "center", label: "Center" },
      { value: "right", label: "Right" },
    ],
  },
  {
    key: "verticalAlign",
    title: "Vertical Alignment",
    description: "Vertical alignment of text on screen",
    keywords: ["vertical", "align", "top", "middle", "bottom", "center"],
    type: "select",
    category: "typography",
    options: [
      { value: "top", label: "Top" },
      { value: "middle", label: "Middle" },
      { value: "bottom", label: "Bottom" },
    ],
  },
  {
    key: "shadowEnabled",
    title: "Shadow",
    description: "Add a drop shadow behind text for readability",
    keywords: ["shadow", "text", "drop", "depth", "effect", "readability"],
    type: "toggle",
    category: "typography",
  },
  {
    key: "shadowBlur",
    title: "Shadow Blur",
    description: "Softness of the text shadow",
    keywords: ["shadow", "blur", "softness", "spread", "radius"],
    type: "slider",
    category: "typography",
    min: 0,
    max: 20,
    step: 0.5,
    unit: "px",
  },
  {
    key: "shadowOpacity",
    title: "Shadow Opacity",
    description: "Strength of the text shadow",
    keywords: ["shadow", "opacity", "strength", "alpha", "transparency"],
    type: "slider",
    category: "typography",
    min: 0,
    max: 100,
    step: 5,
    unit: "%",
  },
  {
    key: "outlineEnabled",
    title: "Outline",
    description: "Add an outline stroke around text characters",
    keywords: ["outline", "stroke", "border", "text", "edge", "contour"],
    type: "toggle",
    category: "typography",
  },
  {
    key: "outlineWidth",
    title: "Outline Width",
    description: "Thickness of the text outline in pixels",
    keywords: ["outline", "width", "stroke", "thickness", "border"],
    type: "slider",
    category: "typography",
    min: 0,
    max: 10,
    step: 0.5,
    unit: "px",
  },
  {
    key: "outlineColor",
    title: "Outline Color",
    description: "Color of the text outline stroke",
    keywords: ["outline", "color", "stroke", "border", "edge"],
    type: "color",
    category: "typography",
  },
  {
    key: "glowEnabled",
    title: "Text Glow",
    description: "Add a soft glow effect behind text",
    keywords: ["glow", "neon", "text", "light", "bloom", "radiance"],
    type: "toggle",
    category: "typography",
  },
  {
    key: "glowColor",
    title: "Glow Color",
    description: "Color of the text glow effect",
    keywords: ["glow", "color", "neon", "light", "bloom", "tint"],
    type: "color",
    category: "typography",
  },
  {
    key: "textOpacity",
    title: "Text Opacity",
    description: "Opacity of projected text",
    keywords: ["text", "opacity", "transparency", "alpha", "fade"],
    type: "slider",
    category: "typography",
    min: 0,
    max: 100,
    step: 5,
    unit: "%",
  },
  {
    key: "referenceOpacity",
    title: "Reference Opacity",
    description: "Opacity of Bible reference text",
    keywords: ["reference", "opacity", "verse", "citation", "bible", "alpha"],
    type: "slider",
    category: "typography",
    min: 0,
    max: 100,
    step: 5,
    unit: "%",
  },

  // ════════════════ Theme ════════════════
  {
    key: "defaultThemeId",
    title: "Default Theme",
    description: "Theme applied to new projects",
    keywords: ["theme", "default", "template", "preset", "style"],
    type: "input",
    category: "theme",
    placeholder: "worship-royal-sapphire",
  },
  {
    key: "animatedThemesEnabled",
    title: "Animation Enable",
    description: "Enable motion effects in theme backgrounds",
    keywords: ["animated", "theme", "animation", "motion", "background", "dynamic"],
    type: "toggle",
    category: "theme",
  },
  {
    key: "themeTransitionSpeed",
    title: "Animation Speed",
    description: "Speed of theme animations in milliseconds",
    keywords: ["animation", "speed", "theme", "transition", "duration", "motion"],
    type: "slider",
    category: "theme",
    min: 100,
    max: 2000,
    step: 100,
    unit: "ms",
  },
  {
    key: "backgroundOpacity",
    title: "Background Opacity",
    description: "Opacity level of the theme background",
    keywords: ["background", "opacity", "transparency", "alpha", "theme"],
    type: "slider",
    category: "theme",
    min: 0,
    max: 100,
    step: 5,
    unit: "%",
  },
  // ════════════════ Backup ════════════════
  {
    key: "automaticBackup",
    title: "Automatic Backup",
    description: "Create periodic backups automatically",
    keywords: ["backup", "auto", "automatic", "scheduled", "periodic"],
    type: "toggle",
    category: "backup",
  },
  {
    key: "backupInterval",
    title: "Backup Interval",
    description: "Hours between automatic backups",
    keywords: ["backup", "interval", "hours", "frequency", "period"],
    type: "number",
    category: "backup",
    min: 1,
    max: 168,
    unit: "h",
  },
];

export const SETTINGS: SettingDef[] = ALL;
export const CATEGORIES: string[] = [...new Set(ALL.map((s) => s.category))];

export const CATEGORY_META: Record<string, { title: string; icon: LucideIcon }> = {
  general: { title: "General", icon: Settings },
  projection: { title: "Projection", icon: MonitorPlay },
  playlist: { title: "Playlist", icon: ListVideo },
  typography: { title: "Typography", icon: Type },
  theme: { title: "Theme", icon: Sparkles },
  "keyboard-shortcuts": { title: "Keyboard Shortcuts", icon: Keyboard },
  backup: { title: "Backup & Restore", icon: Download },
  about: { title: "About", icon: Info },
};
