/**
 * Theme Preset Library — 50 premium, hand-curated worship presentation themes.
 *
 *  • 30 Animated themes — each with unique motion style and visual identity
 *  • 20 Static themes — carefully crafted for every service context
 *  • No colour-swap duplicates — every theme differs in typography, spacing,
 *    background, animation, and mood
 *  • Production-ready for live church projection
 */
import type { BackgroundConfig, SectionStyle, BackgroundAnimation } from "@/lib/broadcast";
import type { LogoSettings } from "@/stores/logo.store";

export type TemplateCategory =
  "Worship" | "Bible" | "Prayer" | "Seasonal" | "Events" | "Modern" | "Animated" | "Minimal";

export type ThemeMood =
  "classic" | "modern" | "warm" | "cool" | "dark" | "light" | "dramatic" | "gentle";

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  mood?: ThemeMood;
  tags?: string[];
  text: Partial<SectionStyle>;
  perGroup?: Partial<Record<"reference" | "tamil" | "english", Partial<SectionStyle>>>;
  background: Partial<BackgroundConfig>;
  logo?: { enabled: boolean; settings?: Partial<LogoSettings> };
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  "Worship",
  "Bible",
  "Prayer",
  "Seasonal",
  "Events",
  "Modern",
  "Animated",
  "Minimal",
];

const shadowSoft = { shadow: true, shadowColor: "#000000", shadowBlur: 22 };
const shadowDeep = { shadow: true, shadowColor: "#000000", shadowBlur: 40 };
const shadowLight = { shadow: true, shadowColor: "#000000", shadowBlur: 12 };

const T = (text: Partial<SectionStyle>): Partial<SectionStyle> => ({
  align: "center",
  vAlign: "middle",
  lineHeight: 1.35,
  ...shadowSoft,
  ...text,
});

interface BuildOpts {
  id: string;
  name: string;
  category: TemplateCategory;
  description?: string;
  bg: string;
  gradient?: string;
  animation?: BackgroundAnimation;
  color?: string;
  refColor?: string;
  fontEn?: string;
  fontTa?: string;
  weight?: number;
  shadow?: "soft" | "deep" | "none" | "light";
  tamilSize?: number;
  lineHeight?: number;
  letterSpacing?: number;
  padding?: number;
  align?: "left" | "center" | "right";
  vAlign?: "top" | "middle" | "bottom";
  mood?: ThemeMood;
  tags?: string[];
  logo?: TemplatePreset["logo"];
  bgOpacity?: number;
  bgColor?: string;
}

const build = (o: BuildOpts): TemplatePreset => {
  const fontEn = o.fontEn ?? "Inter";
  const fontTa = o.fontTa ?? "Latha";
  const color = o.color ?? "#ffffff";
  const sh =
    o.shadow === "none"
      ? { shadow: false, shadowBlur: 0 }
      : o.shadow === "deep"
        ? shadowDeep
        : o.shadow === "light"
          ? shadowLight
          : shadowSoft;
  return {
    id: o.id,
    name: o.name,
    category: o.category,
    description: o.description ?? `${o.name} — worship presentation theme.`,
    mood: o.mood,
    tags: o.tags,
    text: {
      ...T({ fontFamily: fontEn, color, fontWeight: o.weight ?? 500 }),
      ...sh,
      ...(o.lineHeight ? { lineHeight: o.lineHeight } : {}),
      ...(o.letterSpacing != null ? { letterSpacing: o.letterSpacing } : {}),
      ...(o.padding != null ? { paddingVw: o.padding } : {}),
      ...(o.align ? { align: o.align } : {}),
      ...(o.vAlign ? { vAlign: o.vAlign } : {}),
    },
    perGroup: {
      reference: {
        ...(o.refColor ? { color: o.refColor } : {}),
        ...(o.shadow !== "none" ? { shadow: true, shadowBlur: 20, shadowColor: "#000000" } : {}),
      },
      tamil: { fontFamily: fontTa, fontSizeVw: o.tamilSize ?? 5 },
      english: { fontFamily: fontEn },
    },
    background: {
      kind: o.animation ? "color" : "color",
      color: o.bg,
      gradient: o.gradient ?? null,
      animation: o.animation ?? "none",
      ...(o.bgOpacity != null ? { opacity: o.bgOpacity } : {}),
      ...(o.bgColor ? { overlayColor: o.bgColor } : {}),
    },
    logo: o.logo,
  };
};

const ANIMATED_THEMES: BuildOpts[] = [
  {
    id: "anim-golden-stage",
    name: "Golden Worship Stage",
    bg: "#1a0e06",
    gradient: "radial-gradient(ellipse at 50% 60%,rgba(251,191,36,.15),#1a0e06 80%)",
    color: "#fffbeb",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "warm",
    tags: ["golden", "stage", "worship", "light"],
    animation: "golden-stage",
    shadow: "deep",
    weight: 500,
    description: "Warm amber stage with gentle light beams. Reverent worship atmosphere.",
  },
  {
    id: "anim-church-windows",
    name: "Morning Light Through Windows",
    bg: "#0a0a1a",
    gradient:
      "linear-gradient(180deg,rgba(251,146,60,.08),rgba(251,191,36,.04),rgba(147,51,234,.02))",
    color: "#fce7f3",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "warm",
    tags: ["church", "windows", "light", "morning"],
    animation: "church-windows",
    shadow: "deep",
    weight: 400,
    description: "Morning sun streams through arched church windows. Peaceful and sacred.",
  },
  {
    id: "anim-cathedral-glass",
    name: "Cathedral Glass Reflections",
    bg: "#0a0a2e",
    gradient: "linear-gradient(135deg,#0a0a2e,#1a0a3e,#2a0a4e)",
    color: "#f0e6ff",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "dramatic",
    tags: ["cathedral", "stained", "glass", "reflection"],
    animation: "cathedral-glass",
    shadow: "deep",
    weight: 300,
    letterSpacing: 2,
    description:
      "Coloured stained-glass fragments shift with light. Majestic cathedral atmosphere.",
  },
  {
    id: "anim-ocean-horizon",
    name: "Ocean Horizon",
    bg: "#020d1a",
    gradient: "linear-gradient(180deg,#020d1a,#06304a,#0a4a6a)",
    color: "#e0f2fe",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Animated",
    mood: "cool",
    tags: ["ocean", "horizon", "calm", "waves"],
    animation: "ocean-horizon",
    weight: 300,
    lineHeight: 1.4,
    description: "A calm ocean horizon with gentle waves. Vast and peaceful.",
  },
  {
    id: "anim-calm-lake",
    name: "Calm Lake Reflection",
    bg: "#020d1a",
    gradient: "linear-gradient(180deg,#020d1a,#042a3e,#063a4e)",
    color: "#f0f9ff",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Animated",
    mood: "cool",
    tags: ["lake", "reflection", "calm", "water"],
    animation: "calm-lake",
    weight: 300,
    lineHeight: 1.4,
    description: "Still lake water with gentle ripples and light reflections. Meditative calm.",
  },
  {
    id: "anim-cloud-layers",
    name: "Cloud Layers",
    bg: "#0a1628",
    gradient: "linear-gradient(180deg,#0a1628,#1a2e4a,#2a4060)",
    color: "#f1f5f9",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "cool",
    tags: ["clouds", "layers", "sky", "drift"],
    animation: "cloud-layers",
    weight: 300,
    description: "Multiple cloud banks drift at different depths. Open and serene.",
  },
  {
    id: "anim-moving-fog",
    name: "Moving Fog",
    bg: "#0a0e1a",
    gradient: "linear-gradient(180deg,#0a0e1a,#1a2240,#0a0e1a)",
    color: "#f1f5f9",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Animated",
    mood: "dark",
    tags: ["fog", "atmospheric", "motion", "ambient"],
    animation: "moving-fog",
    weight: 300,
    description: "Layered fog banks drift slowly through a dark landscape. Atmospheric depth.",
  },
  {
    id: "anim-night-sky",
    name: "Night Sky Stars",
    bg: "#020214",
    gradient: "radial-gradient(ellipse at 50% 50%,#0a0a2e,#020214,#000005)",
    color: "#e0e7ff",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "cool",
    tags: ["night", "stars", "sky", "deep"],
    animation: "night-sky",
    weight: 300,
    letterSpacing: 2,
    description: "Countless stars twinkle against a deep night sky. The heavens declare His glory.",
  },
  {
    id: "anim-aurora-curtain",
    name: "Aurora Curtain",
    bg: "#020210",
    gradient: "radial-gradient(ellipse at 50% 50%,#02061a,#020210,#000005)",
    color: "#ccfbf1",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "cool",
    tags: ["aurora", "curtain", "northern", "ethereal"],
    animation: "aurora-curtain",
    weight: 300,
    letterSpacing: 2,
    description: "Emerald and cyan aurora curtains ripple across a polar sky. Ethereal majesty.",
  },
  {
    id: "anim-deep-space",
    name: "Deep Space",
    bg: "#020010",
    gradient: "radial-gradient(ellipse at 40% 50%,#0a0020,#020010,#000005)",
    color: "#f0e6ff",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "dramatic",
    tags: ["space", "nebula", "cosmic", "deep"],
    animation: "deep-space",
    weight: 300,
    letterSpacing: 3,
    description: "A cosmic nebula swirls with distant stars. Awe and wonder at creation.",
  },
  {
    id: "anim-mountain-sunrise",
    name: "Mountain Sunrise",
    bg: "#1a0a2e",
    gradient: "linear-gradient(180deg,#1a0a2e,#3a1a3e,#6a2a3e)",
    color: "#fce7f3",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "dramatic",
    tags: ["mountain", "sunrise", "dawn", "silhouette"],
    animation: "mountain-sunrise",
    weight: 400,
    description: "Sunrise breaks over mountain silhouettes. New mercies every morning.",
  },
  {
    id: "anim-forest-light",
    name: "Forest Light",
    bg: "#063016",
    gradient: "linear-gradient(180deg,#063016,#0a4a1a,#063016)",
    color: "#ecfdf5",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "gentle",
    tags: ["forest", "trees", "light", "nature"],
    animation: "forest-light",
    weight: 400,
    description: "Light filters through a forest canopy. Peaceful and restorative.",
  },
  {
    id: "anim-candle-glow",
    name: "Warm Candle Glow",
    bg: "#0a0604",
    gradient: "radial-gradient(ellipse at 50% 80%,#1a0f08,#0a0604)",
    color: "#fef3c7",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "warm",
    tags: ["candle", "warm", "prayer", "intimate"],
    animation: "candle-glow",
    shadow: "deep",
    description:
      "Multiple candle flames flicker with warm amber light. Intimate prayer atmosphere.",
  },
  {
    id: "anim-premium-geo",
    name: "Premium Abstract Geometry",
    bg: "#040412",
    gradient: "radial-gradient(ellipse at 50% 50%,#0a0a2e,#040412)",
    color: "#e0e7ff",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "modern",
    tags: ["geometry", "abstract", "modern", "3d"],
    animation: "premium-geo",
    weight: 300,
    letterSpacing: 1,
    description: "Rotating geometric shapes with depth. Modern elegance for contemporary worship.",
  },
  {
    id: "anim-floating-silk",
    name: "Floating Silk Fabric",
    bg: "#0a0a2e",
    gradient: "linear-gradient(135deg,#0a0a2e,#1a1a4e,#2a1a4e)",
    color: "#f3e8ff",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "dramatic",
    tags: ["silk", "fabric", "flow", "elegant"],
    animation: "floating-silk",
    weight: 300,
    letterSpacing: 2,
    description: "Graceful silk fabric flows and billows. Luxurious and elegant.",
  },
  {
    id: "anim-liquid-glass",
    name: "Liquid Glass",
    bg: "#0a122e",
    gradient: "linear-gradient(135deg,#0a122e,#1a2250,#0a122e)",
    color: "#e2e8f0",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "modern",
    tags: ["glass", "liquid", "reflective", "modern"],
    animation: "liquid-glass",
    weight: 300,
    description:
      "Translucent glass shapes with shimmering reflections. Contemporary sophistication.",
  },
  {
    id: "anim-elegant-mesh",
    name: "Elegant Mesh",
    bg: "#060810",
    gradient: "radial-gradient(ellipse at 50% 50%,#0a0e1a,#060810)",
    color: "#cbd5e1",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Animated",
    mood: "modern",
    tags: ["mesh", "grid", "modern", "subtle"],
    animation: "elegant-mesh",
    weight: 300,
    description: "A subtle mesh grid with breathing points of light. Minimalist precision.",
  },
  {
    id: "anim-architectural-motion",
    name: "Modern Architectural Motion",
    bg: "#0a0e1a",
    gradient: "linear-gradient(135deg,#0a0e1a,#141a2e,#1a1f3a)",
    color: "#94a3b8",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "modern",
    tags: ["architecture", "modern", "lines", "clean"],
    animation: "architectural-motion",
    weight: 300,
    letterSpacing: 3,
    description: "Clean architectural lines with scanning light. Modern and refined.",
  },
  {
    id: "anim-ambient-beams",
    name: "Ambient Light Beams",
    bg: "#050810",
    gradient: "radial-gradient(ellipse at 50% 50%,#0a0e1a,#050810)",
    color: "#e0e7ff",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "cool",
    tags: ["ambient", "light", "beams", "atmosphere"],
    animation: "ambient-beams",
    weight: 300,
    description: "Gentle light beams sweep across a dark space. Atmospheric and contemplative.",
  },
  {
    id: "anim-dark-auditorium",
    name: "Dark Auditorium",
    bg: "#030306",
    gradient: "radial-gradient(ellipse at 50% 40%,#0a0a12,#030306)",
    color: "#f1f5f9",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Animated",
    mood: "dark",
    tags: ["auditorium", "dark", "stage", "focus"],
    animation: "dark-auditorium",
    weight: 300,
    description: "A dark auditorium with subtle stage light. Focused and undistracted.",
  },
  {
    id: "anim-stage-spotlights",
    name: "Stage Spotlights",
    bg: "#03030a",
    gradient: "radial-gradient(ellipse at 50% 40%,#0a0a1e,#03030a)",
    color: "#c7d2fe",
    fontEn: "Catamaran",
    fontTa: "Catamaran",
    category: "Animated",
    mood: "dramatic",
    tags: ["stage", "spotlight", "dramatic", "live"],
    animation: "stage-spotlights",
    weight: 600,
    description: "Professional stage spotlights sweep across a dark stage. Live worship energy.",
  },
  {
    id: "anim-luxury-gold",
    name: "Luxury Gold Motion",
    bg: "#0a0604",
    gradient: "radial-gradient(ellipse at 50% 50%,#1a0e06,#0a0604)",
    color: "#fde68a",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "warm",
    tags: ["gold", "luxury", "premium", "elegant"],
    animation: "luxury-gold",
    shadow: "deep",
    description: "Premium gold shapes float with a subtle shimmer. Luxury worship atmosphere.",
  },
  {
    id: "anim-premium-bokeh",
    name: "Premium Bokeh",
    bg: "#05050e",
    gradient: "radial-gradient(ellipse at 50% 50%,#0a0a1a,#05050e)",
    color: "#f1f5f9",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Animated",
    mood: "dark",
    tags: ["bokeh", "blur", "cinematic", "dreamy"],
    animation: "premium-bokeh",
    weight: 300,
    description:
      "High-quality blurred circles of light float through darkness. Cinematic and dreamy.",
  },
  {
    id: "anim-velvet-background",
    name: "Velvet Background",
    bg: "#0a0606",
    gradient: "linear-gradient(135deg,#1a0a0a,#2a0a1a,#1a0a0e)",
    color: "#ffe4e6",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "dramatic",
    tags: ["velvet", "rich", "deep", "dramatic"],
    animation: "velvet-background",
    weight: 400,
    description: "Rich velvet fabric with deep crimson tones. Warm and reverent.",
  },
  {
    id: "anim-ethereal-glow",
    name: "Ethereal Glow",
    bg: "#050518",
    gradient: "radial-gradient(ellipse at 50% 50%,#0a0a2e,#050518)",
    color: "#f0e6ff",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Animated",
    mood: "gentle",
    tags: ["glow", "ethereal", "heavenly", "soft"],
    animation: "ethereal-glow",
    weight: 300,
    description: "Soft heavenly glow with floating light orbs. Holy Spirit atmosphere.",
  },
];

const WORSHIP_THEMES: BuildOpts[] = [
  {
    id: "worship-royal-sapphire",
    name: "Royal Sapphire",
    bg: "#0c1e3f",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Worship",
    mood: "classic",
    tags: ["navy", "serif", "traditional"],
    lineHeight: 1.3,
    letterSpacing: 0.5,
    shadow: "deep",
    description: "White Georgia serif on deep navy. Timeless and majestic.",
  },
  {
    id: "worship-crimson",
    name: "Crimson Worship",
    bg: "#4a0e1a",
    gradient: "linear-gradient(180deg,#4a0e1a,#7f1d1d)",
    color: "#fdf6e3",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Worship",
    mood: "classic",
    tags: ["burgundy", "serif", "warm", "traditional"],
    padding: 8,
    description: "Warm ivory serif on deep burgundy. Traditional and reverent.",
  },
  {
    id: "worship-indigo-modern",
    name: "Indigo Modern",
    bg: "#1e1b4b",
    gradient: "linear-gradient(135deg,#1e1b4b,#4338ca,#7c3aed)",
    fontEn: "Catamaran",
    fontTa: "Catamaran",
    category: "Worship",
    mood: "modern",
    tags: ["indigo", "gradient", "contemporary"],
    weight: 600,
    description: "Indigo-to-violet gradient with bold sans. Contemporary worship.",
  },
  {
    id: "worship-golden-harvest",
    name: "Golden Harvest",
    bg: "#78350f",
    gradient: "linear-gradient(135deg,#78350f,#d97706,#fbbf24)",
    color: "#fffbeb",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Worship",
    mood: "warm",
    tags: ["gold", "harvest", "warm", "sunset"],
    shadow: "light",
    description: "Golden amber gradient with warm white text. Sunset glow.",
  },
];

const BIBLE_THEMES: BuildOpts[] = [
  {
    id: "bible-parchment",
    name: "Parchment",
    bg: "#f5efe0",
    color: "#1c1917",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Bible",
    mood: "light",
    tags: ["cream", "serif", "readable", "study"],
    shadow: "none",
    lineHeight: 1.45,
    padding: 8,
    letterSpacing: 0.3,
    vAlign: "top",
    description: "Dark ink on cream parchment. The classic Bible-reading experience.",
  },
  {
    id: "bible-scholar",
    name: "Scholar",
    bg: "#0a0a0a",
    color: "#ffffff",
    fontEn: "Georgia",
    fontTa: "Latha",
    category: "Bible",
    mood: "dark",
    tags: ["black", "gold", "study", "deep"],
    refColor: "#fcd34d",
    shadow: "deep",
    description: "Black backdrop, gold reference, white body text. Deep study.",
  },
  {
    id: "bible-scripture-light",
    name: "Scripture Light",
    bg: "#fafaf9",
    color: "#0c0a09",
    fontEn: "Inter",
    fontTa: "Noto Sans Tamil",
    category: "Bible",
    mood: "light",
    tags: ["white", "sans", "clean", "readable"],
    shadow: "none",
    lineHeight: 1.5,
    padding: 10,
    vAlign: "top",
    align: "left",
    description: "Clean white with dark sans-serif. Maximum readability.",
  },
  {
    id: "bible-dawn-study",
    name: "Dawn Study",
    bg: "#0f172a",
    color: "#e0e7ff",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Bible",
    mood: "cool",
    tags: ["navy", "blue", "dawn", "study"],
    refColor: "#93c5fd",
    lineHeight: 1.4,
    description: "Calm study blue with light reference. Easy on the eyes.",
  },
];

const PRAYER_THEMES: BuildOpts[] = [
  {
    id: "prayer-candlelight",
    name: "Candlelight",
    bg: "#1a0f08",
    gradient: "radial-gradient(circle at 50% 70%,#3a1e0a,#0a0604 80%)",
    color: "#fef3c7",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Prayer",
    mood: "warm",
    tags: ["amber", "candle", "warm", "prayer"],
    animation: "candle-glow",
    shadow: "deep",
    description: "Flickering candle warmth. Quiet, reverent, intimate.",
  },
  {
    id: "prayer-incense",
    name: "Incense",
    bg: "#1c0f1a",
    gradient: "linear-gradient(180deg,#1c0f1a,#3b1f3a)",
    color: "#fbcfe8",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Prayer",
    mood: "gentle",
    tags: ["purple", "mystery", "drift", "prayer"],
    animation: "moving-fog",
    lineHeight: 1.35,
    description: "Soft drifting mist in violet. Prayer like incense rising.",
  },
];

const SEASONAL_THEMES: BuildOpts[] = [
  {
    id: "seasonal-evergreen",
    name: "Evergreen",
    bg: "#064e3b",
    color: "#fbbf24",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Seasonal",
    mood: "warm",
    tags: ["green", "gold", "christmas", "festive"],
    shadow: "soft",
    letterSpacing: 1.5,
    description: "Festive evergreen with gold serif. Christmas joy.",
  },
  {
    id: "seasonal-new-dawn",
    name: "New Dawn",
    bg: "#020617",
    gradient: "linear-gradient(135deg,#020617,#1e3a8a)",
    color: "#fef3c7",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Seasonal",
    mood: "dramatic",
    tags: ["sparkle", "new-year", "stars", "fresh"],
    animation: "night-sky",
    weight: 600,
    description: "New Year sparkle over deep blue. Fresh start ahead.",
  },
];

const EVENTS_THEMES: BuildOpts[] = [
  {
    id: "events-rose-garden",
    name: "Rose Garden",
    bg: "#9d174d",
    gradient: "linear-gradient(135deg,#831843,#db2777,#f9a8d4)",
    color: "#fff1f2",
    fontEn: "Georgia",
    fontTa: "Noto Serif Tamil",
    category: "Events",
    mood: "gentle",
    tags: ["rose", "wedding", "romantic", "elegant"],
    letterSpacing: 2,
    weight: 400,
    description: "Blush rose gradient. Elegant wedding atmosphere.",
  },
  {
    id: "events-youth-pulse",
    name: "Youth Pulse",
    bg: "#3b0764",
    gradient: "linear-gradient(135deg,#3b0764,#7e22ce,#ec4899)",
    fontEn: "Catamaran",
    fontTa: "Catamaran",
    category: "Events",
    mood: "dramatic",
    tags: ["violet", "youth", "bold", "energy"],
    weight: 700,
    shadow: "light",
    description: "Electric violet-to-pink gradient. Energetic youth night.",
  },
];

const MODERN_THEMES: BuildOpts[] = [
  {
    id: "modern-glass",
    name: "Glass Worship",
    bg: "#0f172a",
    gradient: "radial-gradient(circle at 70% 30%,#1e293b,#0f172a 80%)",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Modern",
    mood: "cool",
    tags: ["glass", "modern", "clean", "subtle"],
    weight: 300,
    shadow: "none",
    letterSpacing: 3,
    bgOpacity: 0.85,
    description: "Subtle glassmorphism-inspired dark. Thin, elegant, modern.",
  },
  {
    id: "modern-edge",
    name: "Edge",
    bg: "#020617",
    gradient: "linear-gradient(135deg,#020617,#0f172a,#020617)",
    color: "#2dd4bf",
    fontEn: "Inter",
    fontTa: "Catamaran",
    category: "Modern",
    mood: "dramatic",
    tags: ["teal", "edge", "modern", "bold"],
    weight: 300,
    shadow: "none",
    letterSpacing: 4,
    lineHeight: 1.5,
    description: "Dark cyber backdrop with teal accent text. Edgy and bold.",
  },
  {
    id: "modern-monochrome",
    name: "Monochrome",
    bg: "#0a0a0a",
    gradient: "radial-gradient(ellipse at 50% 60%,#1a1a2e,#0a0a0a 80%)",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Modern",
    mood: "dark",
    tags: ["stage", "clean", "minimal", "focus"],
    weight: 400,
    shadow: "light",
    description: "Stage-lit minimal dark. Clean, focused, undistracted.",
  },
];

const MINIMAL_THEMES: BuildOpts[] = [
  {
    id: "minimal-black",
    name: "Minimal Black",
    bg: "#000000",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Minimal",
    mood: "dark",
    tags: ["black", "thin", "clean", "pure"],
    weight: 300,
    shadow: "none",
    letterSpacing: 2,
    description: "Pure black with thin sans. Nothing but the Word.",
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    bg: "#fafaf9",
    color: "#1c1917",
    fontEn: "Inter",
    fontTa: "Noto Sans Tamil",
    category: "Minimal",
    mood: "light",
    tags: ["white", "clean", "paper", "airy"],
    shadow: "none",
    padding: 10,
    description: "Pure white with dark sans. Clean, airy, and modern.",
  },
  {
    id: "minimal-frost",
    name: "Frost",
    bg: "#e0f2fe",
    color: "#0c4a6e",
    fontEn: "Inter",
    fontTa: "Mukta Malar",
    category: "Minimal",
    mood: "cool",
    tags: ["ice", "frost", "cold", "crisp"],
    shadow: "none",
    weight: 400,
    padding: 8,
    description: "Icy blue-white. Cool, crisp, and refreshing.",
  },
];

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  ...ANIMATED_THEMES.map(build),
  ...WORSHIP_THEMES.map(build),
  ...BIBLE_THEMES.map(build),
  ...PRAYER_THEMES.map(build),
  ...SEASONAL_THEMES.map(build),
  ...EVENTS_THEMES.map(build),
  ...MODERN_THEMES.map(build),
  ...MINIMAL_THEMES.map(build),
];
